// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface CapabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.CapabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Supported schema models.
   * </pre>
   *
   * <code>repeated .gnmi.ModelData supported_models = 1;</code>
   */
  java.util.List<com.github.gnmi.proto.ModelData> 
      getSupportedModelsList();
  /**
   * <pre>
   * Supported schema models.
   * </pre>
   *
   * <code>repeated .gnmi.ModelData supported_models = 1;</code>
   */
  com.github.gnmi.proto.ModelData getSupportedModels(int index);
  /**
   * <pre>
   * Supported schema models.
   * </pre>
   *
   * <code>repeated .gnmi.ModelData supported_models = 1;</code>
   */
  int getSupportedModelsCount();
  /**
   * <pre>
   * Supported schema models.
   * </pre>
   *
   * <code>repeated .gnmi.ModelData supported_models = 1;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.ModelDataOrBuilder> 
      getSupportedModelsOrBuilderList();
  /**
   * <pre>
   * Supported schema models.
   * </pre>
   *
   * <code>repeated .gnmi.ModelData supported_models = 1;</code>
   */
  com.github.gnmi.proto.ModelDataOrBuilder getSupportedModelsOrBuilder(
      int index);

  /**
   * <pre>
   * Supported encodings.
   * </pre>
   *
   * <code>repeated .gnmi.Encoding supported_encodings = 2;</code>
   */
  java.util.List<com.github.gnmi.proto.Encoding> getSupportedEncodingsList();
  /**
   * <pre>
   * Supported encodings.
   * </pre>
   *
   * <code>repeated .gnmi.Encoding supported_encodings = 2;</code>
   */
  int getSupportedEncodingsCount();
  /**
   * <pre>
   * Supported encodings.
   * </pre>
   *
   * <code>repeated .gnmi.Encoding supported_encodings = 2;</code>
   */
  com.github.gnmi.proto.Encoding getSupportedEncodings(int index);
  /**
   * <pre>
   * Supported encodings.
   * </pre>
   *
   * <code>repeated .gnmi.Encoding supported_encodings = 2;</code>
   */
  java.util.List<java.lang.Integer>
  getSupportedEncodingsValueList();
  /**
   * <pre>
   * Supported encodings.
   * </pre>
   *
   * <code>repeated .gnmi.Encoding supported_encodings = 2;</code>
   */
  int getSupportedEncodingsValue(int index);

  /**
   * <pre>
   * Supported gNMI version.
   * </pre>
   *
   * <code>string gNMI_version = 3;</code>
   */
  java.lang.String getGNMIVersion();
  /**
   * <pre>
   * Supported gNMI version.
   * </pre>
   *
   * <code>string gNMI_version = 3;</code>
   */
  com.google.protobuf.ByteString
      getGNMIVersionBytes();

  /**
   * <pre>
   * Extension messages associated with the CapabilityResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 4;</code>
   */
  java.util.List<gnmi_ext.GnmiExt.Extension> 
      getExtensionList();
  /**
   * <pre>
   * Extension messages associated with the CapabilityResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 4;</code>
   */
  gnmi_ext.GnmiExt.Extension getExtension(int index);
  /**
   * <pre>
   * Extension messages associated with the CapabilityResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 4;</code>
   */
  int getExtensionCount();
  /**
   * <pre>
   * Extension messages associated with the CapabilityResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 4;</code>
   */
  java.util.List<? extends gnmi_ext.GnmiExt.ExtensionOrBuilder> 
      getExtensionOrBuilderList();
  /**
   * <pre>
   * Extension messages associated with the CapabilityResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 4;</code>
   */
  gnmi_ext.GnmiExt.ExtensionOrBuilder getExtensionOrBuilder(
      int index);
}
