// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Data values.
   * </pre>
   *
   * <code>repeated .gnmi.Notification notification = 1;</code>
   */
  java.util.List<com.github.gnmi.proto.Notification> 
      getNotificationList();
  /**
   * <pre>
   * Data values.
   * </pre>
   *
   * <code>repeated .gnmi.Notification notification = 1;</code>
   */
  com.github.gnmi.proto.Notification getNotification(int index);
  /**
   * <pre>
   * Data values.
   * </pre>
   *
   * <code>repeated .gnmi.Notification notification = 1;</code>
   */
  int getNotificationCount();
  /**
   * <pre>
   * Data values.
   * </pre>
   *
   * <code>repeated .gnmi.Notification notification = 1;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.NotificationOrBuilder> 
      getNotificationOrBuilderList();
  /**
   * <pre>
   * Data values.
   * </pre>
   *
   * <code>repeated .gnmi.Notification notification = 1;</code>
   */
  com.github.gnmi.proto.NotificationOrBuilder getNotificationOrBuilder(
      int index);

  /**
   * <pre>
   * Errors that occurred in the Get.
   * </pre>
   *
   * <code>.gnmi.Error error = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasError();
  /**
   * <pre>
   * Errors that occurred in the Get.
   * </pre>
   *
   * <code>.gnmi.Error error = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.github.gnmi.proto.Error getError();
  /**
   * <pre>
   * Errors that occurred in the Get.
   * </pre>
   *
   * <code>.gnmi.Error error = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.github.gnmi.proto.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * Extension messages associated with the GetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 3;</code>
   */
  java.util.List<gnmi_ext.GnmiExt.Extension> 
      getExtensionList();
  /**
   * <pre>
   * Extension messages associated with the GetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 3;</code>
   */
  gnmi_ext.GnmiExt.Extension getExtension(int index);
  /**
   * <pre>
   * Extension messages associated with the GetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 3;</code>
   */
  int getExtensionCount();
  /**
   * <pre>
   * Extension messages associated with the GetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 3;</code>
   */
  java.util.List<? extends gnmi_ext.GnmiExt.ExtensionOrBuilder> 
      getExtensionOrBuilderList();
  /**
   * <pre>
   * Extension messages associated with the GetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 3;</code>
   */
  gnmi_ext.GnmiExt.ExtensionOrBuilder getExtensionOrBuilder(
      int index);
}
