// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface ModelDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.ModelData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the model.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the model.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Organization publishing the model.
   * </pre>
   *
   * <code>string organization = 2;</code>
   */
  java.lang.String getOrganization();
  /**
   * <pre>
   * Organization publishing the model.
   * </pre>
   *
   * <code>string organization = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrganizationBytes();

  /**
   * <pre>
   * Semantic version of the model.
   * </pre>
   *
   * <code>string version = 3;</code>
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * Semantic version of the model.
   * </pre>
   *
   * <code>string version = 3;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
