// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

/**
 * <pre>
 * Notification is a re-usable message that is used to encode data from the
 * target to the client. A Notification carries two types of changes to the data
 * tree:
 *  - Deleted values (delete) - a set of paths that have been removed from the
 *    data tree.
 *  - Updated values (update) - a set of path-value pairs indicating the path
 *    whose value has changed in the data tree.
 * Reference: gNMI Specification Section 2.1
 * </pre>
 *
 * Protobuf type {@code gnmi.Notification}
 */
public  final class Notification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gnmi.Notification)
    NotificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Notification.newBuilder() to construct.
  private Notification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Notification() {
    timestamp_ = 0L;
    update_ = java.util.Collections.emptyList();
    delete_ = java.util.Collections.emptyList();
    atomic_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Notification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            timestamp_ = input.readInt64();
            break;
          }
          case 18: {
            com.github.gnmi.proto.Path.Builder subBuilder = null;
            if (prefix_ != null) {
              subBuilder = prefix_.toBuilder();
            }
            prefix_ = input.readMessage(com.github.gnmi.proto.Path.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(prefix_);
              prefix_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              update_ = new java.util.ArrayList<com.github.gnmi.proto.Update>();
              mutable_bitField0_ |= 0x00000004;
            }
            update_.add(
                input.readMessage(com.github.gnmi.proto.Update.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              delete_ = new java.util.ArrayList<com.github.gnmi.proto.Path>();
              mutable_bitField0_ |= 0x00000008;
            }
            delete_.add(
                input.readMessage(com.github.gnmi.proto.Path.parser(), extensionRegistry));
            break;
          }
          case 48: {

            atomic_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        update_ = java.util.Collections.unmodifiableList(update_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        delete_ = java.util.Collections.unmodifiableList(delete_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Notification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Notification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.gnmi.proto.Notification.class, com.github.gnmi.proto.Notification.Builder.class);
  }

  private int bitField0_;
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_;
  /**
   * <pre>
   * Timestamp in nanoseconds since Epoch.
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int PREFIX_FIELD_NUMBER = 2;
  private com.github.gnmi.proto.Path prefix_;
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 2;</code>
   */
  public boolean hasPrefix() {
    return prefix_ != null;
  }
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 2;</code>
   */
  public com.github.gnmi.proto.Path getPrefix() {
    return prefix_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
  }
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 2;</code>
   */
  public com.github.gnmi.proto.PathOrBuilder getPrefixOrBuilder() {
    return getPrefix();
  }

  public static final int UPDATE_FIELD_NUMBER = 4;
  private java.util.List<com.github.gnmi.proto.Update> update_;
  /**
   * <pre>
   * Data elements that have changed values.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public java.util.List<com.github.gnmi.proto.Update> getUpdateList() {
    return update_;
  }
  /**
   * <pre>
   * Data elements that have changed values.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
      getUpdateOrBuilderList() {
    return update_;
  }
  /**
   * <pre>
   * Data elements that have changed values.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public int getUpdateCount() {
    return update_.size();
  }
  /**
   * <pre>
   * Data elements that have changed values.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public com.github.gnmi.proto.Update getUpdate(int index) {
    return update_.get(index);
  }
  /**
   * <pre>
   * Data elements that have changed values.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public com.github.gnmi.proto.UpdateOrBuilder getUpdateOrBuilder(
      int index) {
    return update_.get(index);
  }

  public static final int DELETE_FIELD_NUMBER = 5;
  private java.util.List<com.github.gnmi.proto.Path> delete_;
  /**
   * <pre>
   * Data elements that have been deleted.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 5;</code>
   */
  public java.util.List<com.github.gnmi.proto.Path> getDeleteList() {
    return delete_;
  }
  /**
   * <pre>
   * Data elements that have been deleted.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 5;</code>
   */
  public java.util.List<? extends com.github.gnmi.proto.PathOrBuilder> 
      getDeleteOrBuilderList() {
    return delete_;
  }
  /**
   * <pre>
   * Data elements that have been deleted.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 5;</code>
   */
  public int getDeleteCount() {
    return delete_.size();
  }
  /**
   * <pre>
   * Data elements that have been deleted.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 5;</code>
   */
  public com.github.gnmi.proto.Path getDelete(int index) {
    return delete_.get(index);
  }
  /**
   * <pre>
   * Data elements that have been deleted.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 5;</code>
   */
  public com.github.gnmi.proto.PathOrBuilder getDeleteOrBuilder(
      int index) {
    return delete_.get(index);
  }

  public static final int ATOMIC_FIELD_NUMBER = 6;
  private boolean atomic_;
  /**
   * <pre>
   * This notification contains a set of paths that are always updated together
   * referenced by a globally unique prefix.
   * </pre>
   *
   * <code>bool atomic = 6;</code>
   */
  public boolean getAtomic() {
    return atomic_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    if (prefix_ != null) {
      output.writeMessage(2, getPrefix());
    }
    for (int i = 0; i < update_.size(); i++) {
      output.writeMessage(4, update_.get(i));
    }
    for (int i = 0; i < delete_.size(); i++) {
      output.writeMessage(5, delete_.get(i));
    }
    if (atomic_ != false) {
      output.writeBool(6, atomic_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    if (prefix_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPrefix());
    }
    for (int i = 0; i < update_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, update_.get(i));
    }
    for (int i = 0; i < delete_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, delete_.get(i));
    }
    if (atomic_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, atomic_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.gnmi.proto.Notification)) {
      return super.equals(obj);
    }
    com.github.gnmi.proto.Notification other = (com.github.gnmi.proto.Notification) obj;

    boolean result = true;
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && (hasPrefix() == other.hasPrefix());
    if (hasPrefix()) {
      result = result && getPrefix()
          .equals(other.getPrefix());
    }
    result = result && getUpdateList()
        .equals(other.getUpdateList());
    result = result && getDeleteList()
        .equals(other.getDeleteList());
    result = result && (getAtomic()
        == other.getAtomic());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (hasPrefix()) {
      hash = (37 * hash) + PREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getPrefix().hashCode();
    }
    if (getUpdateCount() > 0) {
      hash = (37 * hash) + UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateList().hashCode();
    }
    if (getDeleteCount() > 0) {
      hash = (37 * hash) + DELETE_FIELD_NUMBER;
      hash = (53 * hash) + getDeleteList().hashCode();
    }
    hash = (37 * hash) + ATOMIC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAtomic());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.gnmi.proto.Notification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.Notification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.Notification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.Notification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.Notification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.Notification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.Notification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.Notification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.Notification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.Notification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.Notification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.Notification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.gnmi.proto.Notification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Notification is a re-usable message that is used to encode data from the
   * target to the client. A Notification carries two types of changes to the data
   * tree:
   *  - Deleted values (delete) - a set of paths that have been removed from the
   *    data tree.
   *  - Updated values (update) - a set of path-value pairs indicating the path
   *    whose value has changed in the data tree.
   * Reference: gNMI Specification Section 2.1
   * </pre>
   *
   * Protobuf type {@code gnmi.Notification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gnmi.Notification)
      com.github.gnmi.proto.NotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Notification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.gnmi.proto.Notification.class, com.github.gnmi.proto.Notification.Builder.class);
    }

    // Construct using com.github.gnmi.proto.Notification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUpdateFieldBuilder();
        getDeleteFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;

      if (prefixBuilder_ == null) {
        prefix_ = null;
      } else {
        prefix_ = null;
        prefixBuilder_ = null;
      }
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        updateBuilder_.clear();
      }
      if (deleteBuilder_ == null) {
        delete_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        deleteBuilder_.clear();
      }
      atomic_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Notification_descriptor;
    }

    @java.lang.Override
    public com.github.gnmi.proto.Notification getDefaultInstanceForType() {
      return com.github.gnmi.proto.Notification.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.gnmi.proto.Notification build() {
      com.github.gnmi.proto.Notification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.gnmi.proto.Notification buildPartial() {
      com.github.gnmi.proto.Notification result = new com.github.gnmi.proto.Notification(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.timestamp_ = timestamp_;
      if (prefixBuilder_ == null) {
        result.prefix_ = prefix_;
      } else {
        result.prefix_ = prefixBuilder_.build();
      }
      if (updateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          update_ = java.util.Collections.unmodifiableList(update_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.update_ = update_;
      } else {
        result.update_ = updateBuilder_.build();
      }
      if (deleteBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          delete_ = java.util.Collections.unmodifiableList(delete_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.delete_ = delete_;
      } else {
        result.delete_ = deleteBuilder_.build();
      }
      result.atomic_ = atomic_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.gnmi.proto.Notification) {
        return mergeFrom((com.github.gnmi.proto.Notification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.gnmi.proto.Notification other) {
      if (other == com.github.gnmi.proto.Notification.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasPrefix()) {
        mergePrefix(other.getPrefix());
      }
      if (updateBuilder_ == null) {
        if (!other.update_.isEmpty()) {
          if (update_.isEmpty()) {
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUpdateIsMutable();
            update_.addAll(other.update_);
          }
          onChanged();
        }
      } else {
        if (!other.update_.isEmpty()) {
          if (updateBuilder_.isEmpty()) {
            updateBuilder_.dispose();
            updateBuilder_ = null;
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00000004);
            updateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUpdateFieldBuilder() : null;
          } else {
            updateBuilder_.addAllMessages(other.update_);
          }
        }
      }
      if (deleteBuilder_ == null) {
        if (!other.delete_.isEmpty()) {
          if (delete_.isEmpty()) {
            delete_ = other.delete_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDeleteIsMutable();
            delete_.addAll(other.delete_);
          }
          onChanged();
        }
      } else {
        if (!other.delete_.isEmpty()) {
          if (deleteBuilder_.isEmpty()) {
            deleteBuilder_.dispose();
            deleteBuilder_ = null;
            delete_ = other.delete_;
            bitField0_ = (bitField0_ & ~0x00000008);
            deleteBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDeleteFieldBuilder() : null;
          } else {
            deleteBuilder_.addAllMessages(other.delete_);
          }
        }
      }
      if (other.getAtomic() != false) {
        setAtomic(other.getAtomic());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.gnmi.proto.Notification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.gnmi.proto.Notification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <pre>
     * Timestamp in nanoseconds since Epoch.
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Timestamp in nanoseconds since Epoch.
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp in nanoseconds since Epoch.
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.github.gnmi.proto.Path prefix_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> prefixBuilder_;
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public boolean hasPrefix() {
      return prefixBuilder_ != null || prefix_ != null;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public com.github.gnmi.proto.Path getPrefix() {
      if (prefixBuilder_ == null) {
        return prefix_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
      } else {
        return prefixBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public Builder setPrefix(com.github.gnmi.proto.Path value) {
      if (prefixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        prefix_ = value;
        onChanged();
      } else {
        prefixBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public Builder setPrefix(
        com.github.gnmi.proto.Path.Builder builderForValue) {
      if (prefixBuilder_ == null) {
        prefix_ = builderForValue.build();
        onChanged();
      } else {
        prefixBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public Builder mergePrefix(com.github.gnmi.proto.Path value) {
      if (prefixBuilder_ == null) {
        if (prefix_ != null) {
          prefix_ =
            com.github.gnmi.proto.Path.newBuilder(prefix_).mergeFrom(value).buildPartial();
        } else {
          prefix_ = value;
        }
        onChanged();
      } else {
        prefixBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public Builder clearPrefix() {
      if (prefixBuilder_ == null) {
        prefix_ = null;
        onChanged();
      } else {
        prefix_ = null;
        prefixBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public com.github.gnmi.proto.Path.Builder getPrefixBuilder() {
      
      onChanged();
      return getPrefixFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    public com.github.gnmi.proto.PathOrBuilder getPrefixOrBuilder() {
      if (prefixBuilder_ != null) {
        return prefixBuilder_.getMessageOrBuilder();
      } else {
        return prefix_ == null ?
            com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
      }
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> 
        getPrefixFieldBuilder() {
      if (prefixBuilder_ == null) {
        prefixBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder>(
                getPrefix(),
                getParentForChildren(),
                isClean());
        prefix_ = null;
      }
      return prefixBuilder_;
    }

    private java.util.List<com.github.gnmi.proto.Update> update_ =
      java.util.Collections.emptyList();
    private void ensureUpdateIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        update_ = new java.util.ArrayList<com.github.gnmi.proto.Update>(update_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> updateBuilder_;

    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update> getUpdateList() {
      if (updateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(update_);
      } else {
        return updateBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public int getUpdateCount() {
      if (updateBuilder_ == null) {
        return update_.size();
      } else {
        return updateBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update getUpdate(int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);
      } else {
        return updateBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder setUpdate(
        int index, com.github.gnmi.proto.Update value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.set(index, value);
        onChanged();
      } else {
        updateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder setUpdate(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.set(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(com.github.gnmi.proto.Update value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(value);
        onChanged();
      } else {
        updateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(
        int index, com.github.gnmi.proto.Update value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(index, value);
        onChanged();
      } else {
        updateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(
        com.github.gnmi.proto.Update.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addAllUpdate(
        java.lang.Iterable<? extends com.github.gnmi.proto.Update> values) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, update_);
        onChanged();
      } else {
        updateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder clearUpdate() {
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        updateBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder removeUpdate(int index) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.remove(index);
        onChanged();
      } else {
        updateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update.Builder getUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.UpdateOrBuilder getUpdateOrBuilder(
        int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);  } else {
        return updateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
         getUpdateOrBuilderList() {
      if (updateBuilder_ != null) {
        return updateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(update_);
      }
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update.Builder addUpdateBuilder() {
      return getUpdateFieldBuilder().addBuilder(
          com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update.Builder addUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().addBuilder(
          index, com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Data elements that have changed values.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update.Builder> 
         getUpdateBuilderList() {
      return getUpdateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> 
        getUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        updateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder>(
                update_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      return updateBuilder_;
    }

    private java.util.List<com.github.gnmi.proto.Path> delete_ =
      java.util.Collections.emptyList();
    private void ensureDeleteIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        delete_ = new java.util.ArrayList<com.github.gnmi.proto.Path>(delete_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> deleteBuilder_;

    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public java.util.List<com.github.gnmi.proto.Path> getDeleteList() {
      if (deleteBuilder_ == null) {
        return java.util.Collections.unmodifiableList(delete_);
      } else {
        return deleteBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public int getDeleteCount() {
      if (deleteBuilder_ == null) {
        return delete_.size();
      } else {
        return deleteBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public com.github.gnmi.proto.Path getDelete(int index) {
      if (deleteBuilder_ == null) {
        return delete_.get(index);
      } else {
        return deleteBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder setDelete(
        int index, com.github.gnmi.proto.Path value) {
      if (deleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteIsMutable();
        delete_.set(index, value);
        onChanged();
      } else {
        deleteBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder setDelete(
        int index, com.github.gnmi.proto.Path.Builder builderForValue) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.set(index, builderForValue.build());
        onChanged();
      } else {
        deleteBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder addDelete(com.github.gnmi.proto.Path value) {
      if (deleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteIsMutable();
        delete_.add(value);
        onChanged();
      } else {
        deleteBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder addDelete(
        int index, com.github.gnmi.proto.Path value) {
      if (deleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteIsMutable();
        delete_.add(index, value);
        onChanged();
      } else {
        deleteBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder addDelete(
        com.github.gnmi.proto.Path.Builder builderForValue) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.add(builderForValue.build());
        onChanged();
      } else {
        deleteBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder addDelete(
        int index, com.github.gnmi.proto.Path.Builder builderForValue) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.add(index, builderForValue.build());
        onChanged();
      } else {
        deleteBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder addAllDelete(
        java.lang.Iterable<? extends com.github.gnmi.proto.Path> values) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, delete_);
        onChanged();
      } else {
        deleteBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder clearDelete() {
      if (deleteBuilder_ == null) {
        delete_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        deleteBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public Builder removeDelete(int index) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.remove(index);
        onChanged();
      } else {
        deleteBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public com.github.gnmi.proto.Path.Builder getDeleteBuilder(
        int index) {
      return getDeleteFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public com.github.gnmi.proto.PathOrBuilder getDeleteOrBuilder(
        int index) {
      if (deleteBuilder_ == null) {
        return delete_.get(index);  } else {
        return deleteBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public java.util.List<? extends com.github.gnmi.proto.PathOrBuilder> 
         getDeleteOrBuilderList() {
      if (deleteBuilder_ != null) {
        return deleteBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(delete_);
      }
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public com.github.gnmi.proto.Path.Builder addDeleteBuilder() {
      return getDeleteFieldBuilder().addBuilder(
          com.github.gnmi.proto.Path.getDefaultInstance());
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public com.github.gnmi.proto.Path.Builder addDeleteBuilder(
        int index) {
      return getDeleteFieldBuilder().addBuilder(
          index, com.github.gnmi.proto.Path.getDefaultInstance());
    }
    /**
     * <pre>
     * Data elements that have been deleted.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 5;</code>
     */
    public java.util.List<com.github.gnmi.proto.Path.Builder> 
         getDeleteBuilderList() {
      return getDeleteFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> 
        getDeleteFieldBuilder() {
      if (deleteBuilder_ == null) {
        deleteBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder>(
                delete_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        delete_ = null;
      }
      return deleteBuilder_;
    }

    private boolean atomic_ ;
    /**
     * <pre>
     * This notification contains a set of paths that are always updated together
     * referenced by a globally unique prefix.
     * </pre>
     *
     * <code>bool atomic = 6;</code>
     */
    public boolean getAtomic() {
      return atomic_;
    }
    /**
     * <pre>
     * This notification contains a set of paths that are always updated together
     * referenced by a globally unique prefix.
     * </pre>
     *
     * <code>bool atomic = 6;</code>
     */
    public Builder setAtomic(boolean value) {
      
      atomic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This notification contains a set of paths that are always updated together
     * referenced by a globally unique prefix.
     * </pre>
     *
     * <code>bool atomic = 6;</code>
     */
    public Builder clearAtomic() {
      
      atomic_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gnmi.Notification)
  }

  // @@protoc_insertion_point(class_scope:gnmi.Notification)
  private static final com.github.gnmi.proto.Notification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.gnmi.proto.Notification();
  }

  public static com.github.gnmi.proto.Notification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Notification>
      PARSER = new com.google.protobuf.AbstractParser<Notification>() {
    @java.lang.Override
    public Notification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Notification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Notification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Notification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.gnmi.proto.Notification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

