// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface PathOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.Path)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Elements of the path are no longer encoded as a string, but rather within
   * the elem field as a PathElem message.
   * </pre>
   *
   * <code>repeated string element = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<java.lang.String>
      getElementList();
  /**
   * <pre>
   * Elements of the path are no longer encoded as a string, but rather within
   * the elem field as a PathElem message.
   * </pre>
   *
   * <code>repeated string element = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated int getElementCount();
  /**
   * <pre>
   * Elements of the path are no longer encoded as a string, but rather within
   * the elem field as a PathElem message.
   * </pre>
   *
   * <code>repeated string element = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.lang.String getElement(int index);
  /**
   * <pre>
   * Elements of the path are no longer encoded as a string, but rather within
   * the elem field as a PathElem message.
   * </pre>
   *
   * <code>repeated string element = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getElementBytes(int index);

  /**
   * <pre>
   * Label to disambiguate path.
   * </pre>
   *
   * <code>string origin = 2;</code>
   */
  java.lang.String getOrigin();
  /**
   * <pre>
   * Label to disambiguate path.
   * </pre>
   *
   * <code>string origin = 2;</code>
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <pre>
   * Elements of the path.
   * </pre>
   *
   * <code>repeated .gnmi.PathElem elem = 3;</code>
   */
  java.util.List<com.github.gnmi.proto.PathElem> 
      getElemList();
  /**
   * <pre>
   * Elements of the path.
   * </pre>
   *
   * <code>repeated .gnmi.PathElem elem = 3;</code>
   */
  com.github.gnmi.proto.PathElem getElem(int index);
  /**
   * <pre>
   * Elements of the path.
   * </pre>
   *
   * <code>repeated .gnmi.PathElem elem = 3;</code>
   */
  int getElemCount();
  /**
   * <pre>
   * Elements of the path.
   * </pre>
   *
   * <code>repeated .gnmi.PathElem elem = 3;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.PathElemOrBuilder> 
      getElemOrBuilderList();
  /**
   * <pre>
   * Elements of the path.
   * </pre>
   *
   * <code>repeated .gnmi.PathElem elem = 3;</code>
   */
  com.github.gnmi.proto.PathElemOrBuilder getElemOrBuilder(
      int index);

  /**
   * <pre>
   * The name of the target
   * </pre>
   *
   * <code>string target = 4;</code>
   */
  java.lang.String getTarget();
  /**
   * <pre>
   * The name of the target
   * </pre>
   *
   * <code>string target = 4;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
