// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface QOSMarkingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.QOSMarking)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 marking = 1;</code>
   */
  int getMarking();
}
