// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface ScalarArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.ScalarArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The set of elements within the array. Each TypedValue message should
   * specify only elements that have a field identifier of 1-7 (i.e., the
   * values are scalar values).
   * </pre>
   *
   * <code>repeated .gnmi.TypedValue element = 1;</code>
   */
  java.util.List<com.github.gnmi.proto.TypedValue> 
      getElementList();
  /**
   * <pre>
   * The set of elements within the array. Each TypedValue message should
   * specify only elements that have a field identifier of 1-7 (i.e., the
   * values are scalar values).
   * </pre>
   *
   * <code>repeated .gnmi.TypedValue element = 1;</code>
   */
  com.github.gnmi.proto.TypedValue getElement(int index);
  /**
   * <pre>
   * The set of elements within the array. Each TypedValue message should
   * specify only elements that have a field identifier of 1-7 (i.e., the
   * values are scalar values).
   * </pre>
   *
   * <code>repeated .gnmi.TypedValue element = 1;</code>
   */
  int getElementCount();
  /**
   * <pre>
   * The set of elements within the array. Each TypedValue message should
   * specify only elements that have a field identifier of 1-7 (i.e., the
   * values are scalar values).
   * </pre>
   *
   * <code>repeated .gnmi.TypedValue element = 1;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.TypedValueOrBuilder> 
      getElementOrBuilderList();
  /**
   * <pre>
   * The set of elements within the array. Each TypedValue message should
   * specify only elements that have a field identifier of 1-7 (i.e., the
   * values are scalar values).
   * </pre>
   *
   * <code>repeated .gnmi.TypedValue element = 1;</code>
   */
  com.github.gnmi.proto.TypedValueOrBuilder getElementOrBuilder(
      int index);
}
