// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

/**
 * <pre>
 * SetRequest is sent from a client to the target to update values in the data
 * tree. Paths are either deleted by the client, or modified by means of being
 * updated, or replaced. Where a replace is used, unspecified values are
 * considered to be replaced, whereas when update is used the changes are
 * considered to be incremental. The set of changes that are specified within
 * a single SetRequest are considered to be a transaction.
 * Reference: gNMI Specification Section 3.4.1
 * </pre>
 *
 * Protobuf type {@code gnmi.SetRequest}
 */
public  final class SetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gnmi.SetRequest)
    SetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetRequest.newBuilder() to construct.
  private SetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetRequest() {
    delete_ = java.util.Collections.emptyList();
    replace_ = java.util.Collections.emptyList();
    update_ = java.util.Collections.emptyList();
    unionReplace_ = java.util.Collections.emptyList();
    extension_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.github.gnmi.proto.Path.Builder subBuilder = null;
            if (prefix_ != null) {
              subBuilder = prefix_.toBuilder();
            }
            prefix_ = input.readMessage(com.github.gnmi.proto.Path.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(prefix_);
              prefix_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              delete_ = new java.util.ArrayList<com.github.gnmi.proto.Path>();
              mutable_bitField0_ |= 0x00000002;
            }
            delete_.add(
                input.readMessage(com.github.gnmi.proto.Path.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              replace_ = new java.util.ArrayList<com.github.gnmi.proto.Update>();
              mutable_bitField0_ |= 0x00000004;
            }
            replace_.add(
                input.readMessage(com.github.gnmi.proto.Update.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              update_ = new java.util.ArrayList<com.github.gnmi.proto.Update>();
              mutable_bitField0_ |= 0x00000008;
            }
            update_.add(
                input.readMessage(com.github.gnmi.proto.Update.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              extension_ = new java.util.ArrayList<gnmi_ext.GnmiExt.Extension>();
              mutable_bitField0_ |= 0x00000020;
            }
            extension_.add(
                input.readMessage(gnmi_ext.GnmiExt.Extension.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              unionReplace_ = new java.util.ArrayList<com.github.gnmi.proto.Update>();
              mutable_bitField0_ |= 0x00000010;
            }
            unionReplace_.add(
                input.readMessage(com.github.gnmi.proto.Update.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        delete_ = java.util.Collections.unmodifiableList(delete_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        replace_ = java.util.Collections.unmodifiableList(replace_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        update_ = java.util.Collections.unmodifiableList(update_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        extension_ = java.util.Collections.unmodifiableList(extension_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        unionReplace_ = java.util.Collections.unmodifiableList(unionReplace_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.gnmi.proto.SetRequest.class, com.github.gnmi.proto.SetRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PREFIX_FIELD_NUMBER = 1;
  private com.github.gnmi.proto.Path prefix_;
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  public boolean hasPrefix() {
    return prefix_ != null;
  }
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  public com.github.gnmi.proto.Path getPrefix() {
    return prefix_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
  }
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  public com.github.gnmi.proto.PathOrBuilder getPrefixOrBuilder() {
    return getPrefix();
  }

  public static final int DELETE_FIELD_NUMBER = 2;
  private java.util.List<com.github.gnmi.proto.Path> delete_;
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  public java.util.List<com.github.gnmi.proto.Path> getDeleteList() {
    return delete_;
  }
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  public java.util.List<? extends com.github.gnmi.proto.PathOrBuilder> 
      getDeleteOrBuilderList() {
    return delete_;
  }
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  public int getDeleteCount() {
    return delete_.size();
  }
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  public com.github.gnmi.proto.Path getDelete(int index) {
    return delete_.get(index);
  }
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  public com.github.gnmi.proto.PathOrBuilder getDeleteOrBuilder(
      int index) {
    return delete_.get(index);
  }

  public static final int REPLACE_FIELD_NUMBER = 3;
  private java.util.List<com.github.gnmi.proto.Update> replace_;
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  public java.util.List<com.github.gnmi.proto.Update> getReplaceList() {
    return replace_;
  }
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
      getReplaceOrBuilderList() {
    return replace_;
  }
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  public int getReplaceCount() {
    return replace_.size();
  }
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  public com.github.gnmi.proto.Update getReplace(int index) {
    return replace_.get(index);
  }
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  public com.github.gnmi.proto.UpdateOrBuilder getReplaceOrBuilder(
      int index) {
    return replace_.get(index);
  }

  public static final int UPDATE_FIELD_NUMBER = 4;
  private java.util.List<com.github.gnmi.proto.Update> update_;
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public java.util.List<com.github.gnmi.proto.Update> getUpdateList() {
    return update_;
  }
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
      getUpdateOrBuilderList() {
    return update_;
  }
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public int getUpdateCount() {
    return update_.size();
  }
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public com.github.gnmi.proto.Update getUpdate(int index) {
    return update_.get(index);
  }
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  public com.github.gnmi.proto.UpdateOrBuilder getUpdateOrBuilder(
      int index) {
    return update_.get(index);
  }

  public static final int UNION_REPLACE_FIELD_NUMBER = 6;
  private java.util.List<com.github.gnmi.proto.Update> unionReplace_;
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  public java.util.List<com.github.gnmi.proto.Update> getUnionReplaceList() {
    return unionReplace_;
  }
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
      getUnionReplaceOrBuilderList() {
    return unionReplace_;
  }
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  public int getUnionReplaceCount() {
    return unionReplace_.size();
  }
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  public com.github.gnmi.proto.Update getUnionReplace(int index) {
    return unionReplace_.get(index);
  }
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  public com.github.gnmi.proto.UpdateOrBuilder getUnionReplaceOrBuilder(
      int index) {
    return unionReplace_.get(index);
  }

  public static final int EXTENSION_FIELD_NUMBER = 5;
  private java.util.List<gnmi_ext.GnmiExt.Extension> extension_;
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public java.util.List<gnmi_ext.GnmiExt.Extension> getExtensionList() {
    return extension_;
  }
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public java.util.List<? extends gnmi_ext.GnmiExt.ExtensionOrBuilder> 
      getExtensionOrBuilderList() {
    return extension_;
  }
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public int getExtensionCount() {
    return extension_.size();
  }
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public gnmi_ext.GnmiExt.Extension getExtension(int index) {
    return extension_.get(index);
  }
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public gnmi_ext.GnmiExt.ExtensionOrBuilder getExtensionOrBuilder(
      int index) {
    return extension_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (prefix_ != null) {
      output.writeMessage(1, getPrefix());
    }
    for (int i = 0; i < delete_.size(); i++) {
      output.writeMessage(2, delete_.get(i));
    }
    for (int i = 0; i < replace_.size(); i++) {
      output.writeMessage(3, replace_.get(i));
    }
    for (int i = 0; i < update_.size(); i++) {
      output.writeMessage(4, update_.get(i));
    }
    for (int i = 0; i < extension_.size(); i++) {
      output.writeMessage(5, extension_.get(i));
    }
    for (int i = 0; i < unionReplace_.size(); i++) {
      output.writeMessage(6, unionReplace_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (prefix_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPrefix());
    }
    for (int i = 0; i < delete_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, delete_.get(i));
    }
    for (int i = 0; i < replace_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, replace_.get(i));
    }
    for (int i = 0; i < update_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, update_.get(i));
    }
    for (int i = 0; i < extension_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, extension_.get(i));
    }
    for (int i = 0; i < unionReplace_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, unionReplace_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.gnmi.proto.SetRequest)) {
      return super.equals(obj);
    }
    com.github.gnmi.proto.SetRequest other = (com.github.gnmi.proto.SetRequest) obj;

    boolean result = true;
    result = result && (hasPrefix() == other.hasPrefix());
    if (hasPrefix()) {
      result = result && getPrefix()
          .equals(other.getPrefix());
    }
    result = result && getDeleteList()
        .equals(other.getDeleteList());
    result = result && getReplaceList()
        .equals(other.getReplaceList());
    result = result && getUpdateList()
        .equals(other.getUpdateList());
    result = result && getUnionReplaceList()
        .equals(other.getUnionReplaceList());
    result = result && getExtensionList()
        .equals(other.getExtensionList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPrefix()) {
      hash = (37 * hash) + PREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getPrefix().hashCode();
    }
    if (getDeleteCount() > 0) {
      hash = (37 * hash) + DELETE_FIELD_NUMBER;
      hash = (53 * hash) + getDeleteList().hashCode();
    }
    if (getReplaceCount() > 0) {
      hash = (37 * hash) + REPLACE_FIELD_NUMBER;
      hash = (53 * hash) + getReplaceList().hashCode();
    }
    if (getUpdateCount() > 0) {
      hash = (37 * hash) + UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateList().hashCode();
    }
    if (getUnionReplaceCount() > 0) {
      hash = (37 * hash) + UNION_REPLACE_FIELD_NUMBER;
      hash = (53 * hash) + getUnionReplaceList().hashCode();
    }
    if (getExtensionCount() > 0) {
      hash = (37 * hash) + EXTENSION_FIELD_NUMBER;
      hash = (53 * hash) + getExtensionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.gnmi.proto.SetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.SetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.SetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.gnmi.proto.SetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * SetRequest is sent from a client to the target to update values in the data
   * tree. Paths are either deleted by the client, or modified by means of being
   * updated, or replaced. Where a replace is used, unspecified values are
   * considered to be replaced, whereas when update is used the changes are
   * considered to be incremental. The set of changes that are specified within
   * a single SetRequest are considered to be a transaction.
   * Reference: gNMI Specification Section 3.4.1
   * </pre>
   *
   * Protobuf type {@code gnmi.SetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gnmi.SetRequest)
      com.github.gnmi.proto.SetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.gnmi.proto.SetRequest.class, com.github.gnmi.proto.SetRequest.Builder.class);
    }

    // Construct using com.github.gnmi.proto.SetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDeleteFieldBuilder();
        getReplaceFieldBuilder();
        getUpdateFieldBuilder();
        getUnionReplaceFieldBuilder();
        getExtensionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (prefixBuilder_ == null) {
        prefix_ = null;
      } else {
        prefix_ = null;
        prefixBuilder_ = null;
      }
      if (deleteBuilder_ == null) {
        delete_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        deleteBuilder_.clear();
      }
      if (replaceBuilder_ == null) {
        replace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        replaceBuilder_.clear();
      }
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        updateBuilder_.clear();
      }
      if (unionReplaceBuilder_ == null) {
        unionReplace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        unionReplaceBuilder_.clear();
      }
      if (extensionBuilder_ == null) {
        extension_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        extensionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetRequest_descriptor;
    }

    @java.lang.Override
    public com.github.gnmi.proto.SetRequest getDefaultInstanceForType() {
      return com.github.gnmi.proto.SetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.gnmi.proto.SetRequest build() {
      com.github.gnmi.proto.SetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.gnmi.proto.SetRequest buildPartial() {
      com.github.gnmi.proto.SetRequest result = new com.github.gnmi.proto.SetRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (prefixBuilder_ == null) {
        result.prefix_ = prefix_;
      } else {
        result.prefix_ = prefixBuilder_.build();
      }
      if (deleteBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          delete_ = java.util.Collections.unmodifiableList(delete_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.delete_ = delete_;
      } else {
        result.delete_ = deleteBuilder_.build();
      }
      if (replaceBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          replace_ = java.util.Collections.unmodifiableList(replace_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.replace_ = replace_;
      } else {
        result.replace_ = replaceBuilder_.build();
      }
      if (updateBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          update_ = java.util.Collections.unmodifiableList(update_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.update_ = update_;
      } else {
        result.update_ = updateBuilder_.build();
      }
      if (unionReplaceBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          unionReplace_ = java.util.Collections.unmodifiableList(unionReplace_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.unionReplace_ = unionReplace_;
      } else {
        result.unionReplace_ = unionReplaceBuilder_.build();
      }
      if (extensionBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          extension_ = java.util.Collections.unmodifiableList(extension_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.extension_ = extension_;
      } else {
        result.extension_ = extensionBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.gnmi.proto.SetRequest) {
        return mergeFrom((com.github.gnmi.proto.SetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.gnmi.proto.SetRequest other) {
      if (other == com.github.gnmi.proto.SetRequest.getDefaultInstance()) return this;
      if (other.hasPrefix()) {
        mergePrefix(other.getPrefix());
      }
      if (deleteBuilder_ == null) {
        if (!other.delete_.isEmpty()) {
          if (delete_.isEmpty()) {
            delete_ = other.delete_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDeleteIsMutable();
            delete_.addAll(other.delete_);
          }
          onChanged();
        }
      } else {
        if (!other.delete_.isEmpty()) {
          if (deleteBuilder_.isEmpty()) {
            deleteBuilder_.dispose();
            deleteBuilder_ = null;
            delete_ = other.delete_;
            bitField0_ = (bitField0_ & ~0x00000002);
            deleteBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDeleteFieldBuilder() : null;
          } else {
            deleteBuilder_.addAllMessages(other.delete_);
          }
        }
      }
      if (replaceBuilder_ == null) {
        if (!other.replace_.isEmpty()) {
          if (replace_.isEmpty()) {
            replace_ = other.replace_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReplaceIsMutable();
            replace_.addAll(other.replace_);
          }
          onChanged();
        }
      } else {
        if (!other.replace_.isEmpty()) {
          if (replaceBuilder_.isEmpty()) {
            replaceBuilder_.dispose();
            replaceBuilder_ = null;
            replace_ = other.replace_;
            bitField0_ = (bitField0_ & ~0x00000004);
            replaceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReplaceFieldBuilder() : null;
          } else {
            replaceBuilder_.addAllMessages(other.replace_);
          }
        }
      }
      if (updateBuilder_ == null) {
        if (!other.update_.isEmpty()) {
          if (update_.isEmpty()) {
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureUpdateIsMutable();
            update_.addAll(other.update_);
          }
          onChanged();
        }
      } else {
        if (!other.update_.isEmpty()) {
          if (updateBuilder_.isEmpty()) {
            updateBuilder_.dispose();
            updateBuilder_ = null;
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00000008);
            updateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUpdateFieldBuilder() : null;
          } else {
            updateBuilder_.addAllMessages(other.update_);
          }
        }
      }
      if (unionReplaceBuilder_ == null) {
        if (!other.unionReplace_.isEmpty()) {
          if (unionReplace_.isEmpty()) {
            unionReplace_ = other.unionReplace_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureUnionReplaceIsMutable();
            unionReplace_.addAll(other.unionReplace_);
          }
          onChanged();
        }
      } else {
        if (!other.unionReplace_.isEmpty()) {
          if (unionReplaceBuilder_.isEmpty()) {
            unionReplaceBuilder_.dispose();
            unionReplaceBuilder_ = null;
            unionReplace_ = other.unionReplace_;
            bitField0_ = (bitField0_ & ~0x00000010);
            unionReplaceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUnionReplaceFieldBuilder() : null;
          } else {
            unionReplaceBuilder_.addAllMessages(other.unionReplace_);
          }
        }
      }
      if (extensionBuilder_ == null) {
        if (!other.extension_.isEmpty()) {
          if (extension_.isEmpty()) {
            extension_ = other.extension_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureExtensionIsMutable();
            extension_.addAll(other.extension_);
          }
          onChanged();
        }
      } else {
        if (!other.extension_.isEmpty()) {
          if (extensionBuilder_.isEmpty()) {
            extensionBuilder_.dispose();
            extensionBuilder_ = null;
            extension_ = other.extension_;
            bitField0_ = (bitField0_ & ~0x00000020);
            extensionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtensionFieldBuilder() : null;
          } else {
            extensionBuilder_.addAllMessages(other.extension_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.gnmi.proto.SetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.gnmi.proto.SetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.github.gnmi.proto.Path prefix_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> prefixBuilder_;
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public boolean hasPrefix() {
      return prefixBuilder_ != null || prefix_ != null;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public com.github.gnmi.proto.Path getPrefix() {
      if (prefixBuilder_ == null) {
        return prefix_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
      } else {
        return prefixBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder setPrefix(com.github.gnmi.proto.Path value) {
      if (prefixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        prefix_ = value;
        onChanged();
      } else {
        prefixBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder setPrefix(
        com.github.gnmi.proto.Path.Builder builderForValue) {
      if (prefixBuilder_ == null) {
        prefix_ = builderForValue.build();
        onChanged();
      } else {
        prefixBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder mergePrefix(com.github.gnmi.proto.Path value) {
      if (prefixBuilder_ == null) {
        if (prefix_ != null) {
          prefix_ =
            com.github.gnmi.proto.Path.newBuilder(prefix_).mergeFrom(value).buildPartial();
        } else {
          prefix_ = value;
        }
        onChanged();
      } else {
        prefixBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder clearPrefix() {
      if (prefixBuilder_ == null) {
        prefix_ = null;
        onChanged();
      } else {
        prefix_ = null;
        prefixBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public com.github.gnmi.proto.Path.Builder getPrefixBuilder() {
      
      onChanged();
      return getPrefixFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public com.github.gnmi.proto.PathOrBuilder getPrefixOrBuilder() {
      if (prefixBuilder_ != null) {
        return prefixBuilder_.getMessageOrBuilder();
      } else {
        return prefix_ == null ?
            com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
      }
    }
    /**
     * <pre>
     * Prefix used for paths in the message.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> 
        getPrefixFieldBuilder() {
      if (prefixBuilder_ == null) {
        prefixBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder>(
                getPrefix(),
                getParentForChildren(),
                isClean());
        prefix_ = null;
      }
      return prefixBuilder_;
    }

    private java.util.List<com.github.gnmi.proto.Path> delete_ =
      java.util.Collections.emptyList();
    private void ensureDeleteIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        delete_ = new java.util.ArrayList<com.github.gnmi.proto.Path>(delete_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> deleteBuilder_;

    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public java.util.List<com.github.gnmi.proto.Path> getDeleteList() {
      if (deleteBuilder_ == null) {
        return java.util.Collections.unmodifiableList(delete_);
      } else {
        return deleteBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public int getDeleteCount() {
      if (deleteBuilder_ == null) {
        return delete_.size();
      } else {
        return deleteBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public com.github.gnmi.proto.Path getDelete(int index) {
      if (deleteBuilder_ == null) {
        return delete_.get(index);
      } else {
        return deleteBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder setDelete(
        int index, com.github.gnmi.proto.Path value) {
      if (deleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteIsMutable();
        delete_.set(index, value);
        onChanged();
      } else {
        deleteBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder setDelete(
        int index, com.github.gnmi.proto.Path.Builder builderForValue) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.set(index, builderForValue.build());
        onChanged();
      } else {
        deleteBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder addDelete(com.github.gnmi.proto.Path value) {
      if (deleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteIsMutable();
        delete_.add(value);
        onChanged();
      } else {
        deleteBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder addDelete(
        int index, com.github.gnmi.proto.Path value) {
      if (deleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteIsMutable();
        delete_.add(index, value);
        onChanged();
      } else {
        deleteBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder addDelete(
        com.github.gnmi.proto.Path.Builder builderForValue) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.add(builderForValue.build());
        onChanged();
      } else {
        deleteBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder addDelete(
        int index, com.github.gnmi.proto.Path.Builder builderForValue) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.add(index, builderForValue.build());
        onChanged();
      } else {
        deleteBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder addAllDelete(
        java.lang.Iterable<? extends com.github.gnmi.proto.Path> values) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, delete_);
        onChanged();
      } else {
        deleteBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder clearDelete() {
      if (deleteBuilder_ == null) {
        delete_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        deleteBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public Builder removeDelete(int index) {
      if (deleteBuilder_ == null) {
        ensureDeleteIsMutable();
        delete_.remove(index);
        onChanged();
      } else {
        deleteBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public com.github.gnmi.proto.Path.Builder getDeleteBuilder(
        int index) {
      return getDeleteFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public com.github.gnmi.proto.PathOrBuilder getDeleteOrBuilder(
        int index) {
      if (deleteBuilder_ == null) {
        return delete_.get(index);  } else {
        return deleteBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public java.util.List<? extends com.github.gnmi.proto.PathOrBuilder> 
         getDeleteOrBuilderList() {
      if (deleteBuilder_ != null) {
        return deleteBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(delete_);
      }
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public com.github.gnmi.proto.Path.Builder addDeleteBuilder() {
      return getDeleteFieldBuilder().addBuilder(
          com.github.gnmi.proto.Path.getDefaultInstance());
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public com.github.gnmi.proto.Path.Builder addDeleteBuilder(
        int index) {
      return getDeleteFieldBuilder().addBuilder(
          index, com.github.gnmi.proto.Path.getDefaultInstance());
    }
    /**
     * <pre>
     * Paths to be deleted from the data tree.
     * </pre>
     *
     * <code>repeated .gnmi.Path delete = 2;</code>
     */
    public java.util.List<com.github.gnmi.proto.Path.Builder> 
         getDeleteBuilderList() {
      return getDeleteFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> 
        getDeleteFieldBuilder() {
      if (deleteBuilder_ == null) {
        deleteBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder>(
                delete_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        delete_ = null;
      }
      return deleteBuilder_;
    }

    private java.util.List<com.github.gnmi.proto.Update> replace_ =
      java.util.Collections.emptyList();
    private void ensureReplaceIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        replace_ = new java.util.ArrayList<com.github.gnmi.proto.Update>(replace_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> replaceBuilder_;

    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update> getReplaceList() {
      if (replaceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(replace_);
      } else {
        return replaceBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public int getReplaceCount() {
      if (replaceBuilder_ == null) {
        return replace_.size();
      } else {
        return replaceBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public com.github.gnmi.proto.Update getReplace(int index) {
      if (replaceBuilder_ == null) {
        return replace_.get(index);
      } else {
        return replaceBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder setReplace(
        int index, com.github.gnmi.proto.Update value) {
      if (replaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplaceIsMutable();
        replace_.set(index, value);
        onChanged();
      } else {
        replaceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder setReplace(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (replaceBuilder_ == null) {
        ensureReplaceIsMutable();
        replace_.set(index, builderForValue.build());
        onChanged();
      } else {
        replaceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder addReplace(com.github.gnmi.proto.Update value) {
      if (replaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplaceIsMutable();
        replace_.add(value);
        onChanged();
      } else {
        replaceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder addReplace(
        int index, com.github.gnmi.proto.Update value) {
      if (replaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplaceIsMutable();
        replace_.add(index, value);
        onChanged();
      } else {
        replaceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder addReplace(
        com.github.gnmi.proto.Update.Builder builderForValue) {
      if (replaceBuilder_ == null) {
        ensureReplaceIsMutable();
        replace_.add(builderForValue.build());
        onChanged();
      } else {
        replaceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder addReplace(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (replaceBuilder_ == null) {
        ensureReplaceIsMutable();
        replace_.add(index, builderForValue.build());
        onChanged();
      } else {
        replaceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder addAllReplace(
        java.lang.Iterable<? extends com.github.gnmi.proto.Update> values) {
      if (replaceBuilder_ == null) {
        ensureReplaceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, replace_);
        onChanged();
      } else {
        replaceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder clearReplace() {
      if (replaceBuilder_ == null) {
        replace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        replaceBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public Builder removeReplace(int index) {
      if (replaceBuilder_ == null) {
        ensureReplaceIsMutable();
        replace_.remove(index);
        onChanged();
      } else {
        replaceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public com.github.gnmi.proto.Update.Builder getReplaceBuilder(
        int index) {
      return getReplaceFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public com.github.gnmi.proto.UpdateOrBuilder getReplaceOrBuilder(
        int index) {
      if (replaceBuilder_ == null) {
        return replace_.get(index);  } else {
        return replaceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
         getReplaceOrBuilderList() {
      if (replaceBuilder_ != null) {
        return replaceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(replace_);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public com.github.gnmi.proto.Update.Builder addReplaceBuilder() {
      return getReplaceFieldBuilder().addBuilder(
          com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public com.github.gnmi.proto.Update.Builder addReplaceBuilder(
        int index) {
      return getReplaceFieldBuilder().addBuilder(
          index, com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Updates specifying elements to be replaced.
     * </pre>
     *
     * <code>repeated .gnmi.Update replace = 3;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update.Builder> 
         getReplaceBuilderList() {
      return getReplaceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> 
        getReplaceFieldBuilder() {
      if (replaceBuilder_ == null) {
        replaceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder>(
                replace_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        replace_ = null;
      }
      return replaceBuilder_;
    }

    private java.util.List<com.github.gnmi.proto.Update> update_ =
      java.util.Collections.emptyList();
    private void ensureUpdateIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        update_ = new java.util.ArrayList<com.github.gnmi.proto.Update>(update_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> updateBuilder_;

    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update> getUpdateList() {
      if (updateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(update_);
      } else {
        return updateBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public int getUpdateCount() {
      if (updateBuilder_ == null) {
        return update_.size();
      } else {
        return updateBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update getUpdate(int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);
      } else {
        return updateBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder setUpdate(
        int index, com.github.gnmi.proto.Update value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.set(index, value);
        onChanged();
      } else {
        updateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder setUpdate(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.set(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(com.github.gnmi.proto.Update value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(value);
        onChanged();
      } else {
        updateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(
        int index, com.github.gnmi.proto.Update value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(index, value);
        onChanged();
      } else {
        updateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(
        com.github.gnmi.proto.Update.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addUpdate(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder addAllUpdate(
        java.lang.Iterable<? extends com.github.gnmi.proto.Update> values) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, update_);
        onChanged();
      } else {
        updateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder clearUpdate() {
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        updateBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public Builder removeUpdate(int index) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.remove(index);
        onChanged();
      } else {
        updateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update.Builder getUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.UpdateOrBuilder getUpdateOrBuilder(
        int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);  } else {
        return updateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
         getUpdateOrBuilderList() {
      if (updateBuilder_ != null) {
        return updateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(update_);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update.Builder addUpdateBuilder() {
      return getUpdateFieldBuilder().addBuilder(
          com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public com.github.gnmi.proto.Update.Builder addUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().addBuilder(
          index, com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Updates specifying elements to updated.
     * </pre>
     *
     * <code>repeated .gnmi.Update update = 4;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update.Builder> 
         getUpdateBuilderList() {
      return getUpdateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> 
        getUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        updateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder>(
                update_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      return updateBuilder_;
    }

    private java.util.List<com.github.gnmi.proto.Update> unionReplace_ =
      java.util.Collections.emptyList();
    private void ensureUnionReplaceIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        unionReplace_ = new java.util.ArrayList<com.github.gnmi.proto.Update>(unionReplace_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> unionReplaceBuilder_;

    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update> getUnionReplaceList() {
      if (unionReplaceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(unionReplace_);
      } else {
        return unionReplaceBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public int getUnionReplaceCount() {
      if (unionReplaceBuilder_ == null) {
        return unionReplace_.size();
      } else {
        return unionReplaceBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public com.github.gnmi.proto.Update getUnionReplace(int index) {
      if (unionReplaceBuilder_ == null) {
        return unionReplace_.get(index);
      } else {
        return unionReplaceBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder setUnionReplace(
        int index, com.github.gnmi.proto.Update value) {
      if (unionReplaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnionReplaceIsMutable();
        unionReplace_.set(index, value);
        onChanged();
      } else {
        unionReplaceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder setUnionReplace(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (unionReplaceBuilder_ == null) {
        ensureUnionReplaceIsMutable();
        unionReplace_.set(index, builderForValue.build());
        onChanged();
      } else {
        unionReplaceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder addUnionReplace(com.github.gnmi.proto.Update value) {
      if (unionReplaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnionReplaceIsMutable();
        unionReplace_.add(value);
        onChanged();
      } else {
        unionReplaceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder addUnionReplace(
        int index, com.github.gnmi.proto.Update value) {
      if (unionReplaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnionReplaceIsMutable();
        unionReplace_.add(index, value);
        onChanged();
      } else {
        unionReplaceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder addUnionReplace(
        com.github.gnmi.proto.Update.Builder builderForValue) {
      if (unionReplaceBuilder_ == null) {
        ensureUnionReplaceIsMutable();
        unionReplace_.add(builderForValue.build());
        onChanged();
      } else {
        unionReplaceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder addUnionReplace(
        int index, com.github.gnmi.proto.Update.Builder builderForValue) {
      if (unionReplaceBuilder_ == null) {
        ensureUnionReplaceIsMutable();
        unionReplace_.add(index, builderForValue.build());
        onChanged();
      } else {
        unionReplaceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder addAllUnionReplace(
        java.lang.Iterable<? extends com.github.gnmi.proto.Update> values) {
      if (unionReplaceBuilder_ == null) {
        ensureUnionReplaceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unionReplace_);
        onChanged();
      } else {
        unionReplaceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder clearUnionReplace() {
      if (unionReplaceBuilder_ == null) {
        unionReplace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        unionReplaceBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public Builder removeUnionReplace(int index) {
      if (unionReplaceBuilder_ == null) {
        ensureUnionReplaceIsMutable();
        unionReplace_.remove(index);
        onChanged();
      } else {
        unionReplaceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public com.github.gnmi.proto.Update.Builder getUnionReplaceBuilder(
        int index) {
      return getUnionReplaceFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public com.github.gnmi.proto.UpdateOrBuilder getUnionReplaceOrBuilder(
        int index) {
      if (unionReplaceBuilder_ == null) {
        return unionReplace_.get(index);  } else {
        return unionReplaceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
         getUnionReplaceOrBuilderList() {
      if (unionReplaceBuilder_ != null) {
        return unionReplaceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(unionReplace_);
      }
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public com.github.gnmi.proto.Update.Builder addUnionReplaceBuilder() {
      return getUnionReplaceFieldBuilder().addBuilder(
          com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public com.github.gnmi.proto.Update.Builder addUnionReplaceBuilder(
        int index) {
      return getUnionReplaceFieldBuilder().addBuilder(
          index, com.github.gnmi.proto.Update.getDefaultInstance());
    }
    /**
     * <pre>
     * Updates specifying elements to union and then replace the data tree.
     * See the gNMI specification at
     * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
     * for details.
     * </pre>
     *
     * <code>repeated .gnmi.Update union_replace = 6;</code>
     */
    public java.util.List<com.github.gnmi.proto.Update.Builder> 
         getUnionReplaceBuilderList() {
      return getUnionReplaceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder> 
        getUnionReplaceFieldBuilder() {
      if (unionReplaceBuilder_ == null) {
        unionReplaceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.gnmi.proto.Update, com.github.gnmi.proto.Update.Builder, com.github.gnmi.proto.UpdateOrBuilder>(
                unionReplace_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        unionReplace_ = null;
      }
      return unionReplaceBuilder_;
    }

    private java.util.List<gnmi_ext.GnmiExt.Extension> extension_ =
      java.util.Collections.emptyList();
    private void ensureExtensionIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        extension_ = new java.util.ArrayList<gnmi_ext.GnmiExt.Extension>(extension_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        gnmi_ext.GnmiExt.Extension, gnmi_ext.GnmiExt.Extension.Builder, gnmi_ext.GnmiExt.ExtensionOrBuilder> extensionBuilder_;

    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public java.util.List<gnmi_ext.GnmiExt.Extension> getExtensionList() {
      if (extensionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extension_);
      } else {
        return extensionBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public int getExtensionCount() {
      if (extensionBuilder_ == null) {
        return extension_.size();
      } else {
        return extensionBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension getExtension(int index) {
      if (extensionBuilder_ == null) {
        return extension_.get(index);
      } else {
        return extensionBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder setExtension(
        int index, gnmi_ext.GnmiExt.Extension value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.set(index, value);
        onChanged();
      } else {
        extensionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder setExtension(
        int index, gnmi_ext.GnmiExt.Extension.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.set(index, builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(gnmi_ext.GnmiExt.Extension value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.add(value);
        onChanged();
      } else {
        extensionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(
        int index, gnmi_ext.GnmiExt.Extension value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.add(index, value);
        onChanged();
      } else {
        extensionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(
        gnmi_ext.GnmiExt.Extension.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.add(builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(
        int index, gnmi_ext.GnmiExt.Extension.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.add(index, builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addAllExtension(
        java.lang.Iterable<? extends gnmi_ext.GnmiExt.Extension> values) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extension_);
        onChanged();
      } else {
        extensionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder clearExtension() {
      if (extensionBuilder_ == null) {
        extension_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        extensionBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder removeExtension(int index) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.remove(index);
        onChanged();
      } else {
        extensionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension.Builder getExtensionBuilder(
        int index) {
      return getExtensionFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.ExtensionOrBuilder getExtensionOrBuilder(
        int index) {
      if (extensionBuilder_ == null) {
        return extension_.get(index);  } else {
        return extensionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public java.util.List<? extends gnmi_ext.GnmiExt.ExtensionOrBuilder> 
         getExtensionOrBuilderList() {
      if (extensionBuilder_ != null) {
        return extensionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extension_);
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension.Builder addExtensionBuilder() {
      return getExtensionFieldBuilder().addBuilder(
          gnmi_ext.GnmiExt.Extension.getDefaultInstance());
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension.Builder addExtensionBuilder(
        int index) {
      return getExtensionFieldBuilder().addBuilder(
          index, gnmi_ext.GnmiExt.Extension.getDefaultInstance());
    }
    /**
     * <pre>
     * Extension messages associated with the SetRequest. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public java.util.List<gnmi_ext.GnmiExt.Extension.Builder> 
         getExtensionBuilderList() {
      return getExtensionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        gnmi_ext.GnmiExt.Extension, gnmi_ext.GnmiExt.Extension.Builder, gnmi_ext.GnmiExt.ExtensionOrBuilder> 
        getExtensionFieldBuilder() {
      if (extensionBuilder_ == null) {
        extensionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            gnmi_ext.GnmiExt.Extension, gnmi_ext.GnmiExt.Extension.Builder, gnmi_ext.GnmiExt.ExtensionOrBuilder>(
                extension_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        extension_ = null;
      }
      return extensionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gnmi.SetRequest)
  }

  // @@protoc_insertion_point(class_scope:gnmi.SetRequest)
  private static final com.github.gnmi.proto.SetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.gnmi.proto.SetRequest();
  }

  public static com.github.gnmi.proto.SetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetRequest>() {
    @java.lang.Override
    public SetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.gnmi.proto.SetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

