// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface SetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.SetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  boolean hasPrefix();
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  com.github.gnmi.proto.Path getPrefix();
  /**
   * <pre>
   * Prefix used for paths in the message.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  com.github.gnmi.proto.PathOrBuilder getPrefixOrBuilder();

  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  java.util.List<com.github.gnmi.proto.Path> 
      getDeleteList();
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  com.github.gnmi.proto.Path getDelete(int index);
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  int getDeleteCount();
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.PathOrBuilder> 
      getDeleteOrBuilderList();
  /**
   * <pre>
   * Paths to be deleted from the data tree.
   * </pre>
   *
   * <code>repeated .gnmi.Path delete = 2;</code>
   */
  com.github.gnmi.proto.PathOrBuilder getDeleteOrBuilder(
      int index);

  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  java.util.List<com.github.gnmi.proto.Update> 
      getReplaceList();
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  com.github.gnmi.proto.Update getReplace(int index);
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  int getReplaceCount();
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
      getReplaceOrBuilderList();
  /**
   * <pre>
   * Updates specifying elements to be replaced.
   * </pre>
   *
   * <code>repeated .gnmi.Update replace = 3;</code>
   */
  com.github.gnmi.proto.UpdateOrBuilder getReplaceOrBuilder(
      int index);

  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  java.util.List<com.github.gnmi.proto.Update> 
      getUpdateList();
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  com.github.gnmi.proto.Update getUpdate(int index);
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  int getUpdateCount();
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
      getUpdateOrBuilderList();
  /**
   * <pre>
   * Updates specifying elements to updated.
   * </pre>
   *
   * <code>repeated .gnmi.Update update = 4;</code>
   */
  com.github.gnmi.proto.UpdateOrBuilder getUpdateOrBuilder(
      int index);

  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  java.util.List<com.github.gnmi.proto.Update> 
      getUnionReplaceList();
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  com.github.gnmi.proto.Update getUnionReplace(int index);
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  int getUnionReplaceCount();
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  java.util.List<? extends com.github.gnmi.proto.UpdateOrBuilder> 
      getUnionReplaceOrBuilderList();
  /**
   * <pre>
   * Updates specifying elements to union and then replace the data tree.
   * See the gNMI specification at
   * https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md
   * for details.
   * </pre>
   *
   * <code>repeated .gnmi.Update union_replace = 6;</code>
   */
  com.github.gnmi.proto.UpdateOrBuilder getUnionReplaceOrBuilder(
      int index);

  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  java.util.List<gnmi_ext.GnmiExt.Extension> 
      getExtensionList();
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  gnmi_ext.GnmiExt.Extension getExtension(int index);
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  int getExtensionCount();
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  java.util.List<? extends gnmi_ext.GnmiExt.ExtensionOrBuilder> 
      getExtensionOrBuilderList();
  /**
   * <pre>
   * Extension messages associated with the SetRequest. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  gnmi_ext.GnmiExt.ExtensionOrBuilder getExtensionOrBuilder(
      int index);
}
