// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

/**
 * <pre>
 * SetResponse is the response to a SetRequest, sent from the target to the
 * client. It reports the result of the modifications to the data tree that were
 * specified by the client. Errors for this RPC should be reported using the
 * https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto
 * message in the RPC return. The gnmi.Error message can be used to add
 * additional details where required. Reference: gNMI Specification
 * Section 3.4.2
 * </pre>
 *
 * Protobuf type {@code gnmi.SetResponse}
 */
public  final class SetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gnmi.SetResponse)
    SetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetResponse.newBuilder() to construct.
  private SetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetResponse() {
    response_ = java.util.Collections.emptyList();
    timestamp_ = 0L;
    extension_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.github.gnmi.proto.Path.Builder subBuilder = null;
            if (prefix_ != null) {
              subBuilder = prefix_.toBuilder();
            }
            prefix_ = input.readMessage(com.github.gnmi.proto.Path.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(prefix_);
              prefix_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              response_ = new java.util.ArrayList<com.github.gnmi.proto.UpdateResult>();
              mutable_bitField0_ |= 0x00000002;
            }
            response_.add(
                input.readMessage(com.github.gnmi.proto.UpdateResult.parser(), extensionRegistry));
            break;
          }
          case 26: {
            com.github.gnmi.proto.Error.Builder subBuilder = null;
            if (message_ != null) {
              subBuilder = message_.toBuilder();
            }
            message_ = input.readMessage(com.github.gnmi.proto.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(message_);
              message_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            timestamp_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              extension_ = new java.util.ArrayList<gnmi_ext.GnmiExt.Extension>();
              mutable_bitField0_ |= 0x00000010;
            }
            extension_.add(
                input.readMessage(gnmi_ext.GnmiExt.Extension.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        response_ = java.util.Collections.unmodifiableList(response_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        extension_ = java.util.Collections.unmodifiableList(extension_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.gnmi.proto.SetResponse.class, com.github.gnmi.proto.SetResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PREFIX_FIELD_NUMBER = 1;
  private com.github.gnmi.proto.Path prefix_;
  /**
   * <pre>
   * Prefix used for paths.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  public boolean hasPrefix() {
    return prefix_ != null;
  }
  /**
   * <pre>
   * Prefix used for paths.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  public com.github.gnmi.proto.Path getPrefix() {
    return prefix_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
  }
  /**
   * <pre>
   * Prefix used for paths.
   * </pre>
   *
   * <code>.gnmi.Path prefix = 1;</code>
   */
  public com.github.gnmi.proto.PathOrBuilder getPrefixOrBuilder() {
    return getPrefix();
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  private java.util.List<com.github.gnmi.proto.UpdateResult> response_;
  /**
   * <pre>
   * A set of responses specifying the result of the operations specified in
   * the SetRequest.
   * </pre>
   *
   * <code>repeated .gnmi.UpdateResult response = 2;</code>
   */
  public java.util.List<com.github.gnmi.proto.UpdateResult> getResponseList() {
    return response_;
  }
  /**
   * <pre>
   * A set of responses specifying the result of the operations specified in
   * the SetRequest.
   * </pre>
   *
   * <code>repeated .gnmi.UpdateResult response = 2;</code>
   */
  public java.util.List<? extends com.github.gnmi.proto.UpdateResultOrBuilder> 
      getResponseOrBuilderList() {
    return response_;
  }
  /**
   * <pre>
   * A set of responses specifying the result of the operations specified in
   * the SetRequest.
   * </pre>
   *
   * <code>repeated .gnmi.UpdateResult response = 2;</code>
   */
  public int getResponseCount() {
    return response_.size();
  }
  /**
   * <pre>
   * A set of responses specifying the result of the operations specified in
   * the SetRequest.
   * </pre>
   *
   * <code>repeated .gnmi.UpdateResult response = 2;</code>
   */
  public com.github.gnmi.proto.UpdateResult getResponse(int index) {
    return response_.get(index);
  }
  /**
   * <pre>
   * A set of responses specifying the result of the operations specified in
   * the SetRequest.
   * </pre>
   *
   * <code>repeated .gnmi.UpdateResult response = 2;</code>
   */
  public com.github.gnmi.proto.UpdateResultOrBuilder getResponseOrBuilder(
      int index) {
    return response_.get(index);
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private com.github.gnmi.proto.Error message_;
  /**
   * <pre>
   * The overall status of the transaction.
   * </pre>
   *
   * <code>.gnmi.Error message = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated public boolean hasMessage() {
    return message_ != null;
  }
  /**
   * <pre>
   * The overall status of the transaction.
   * </pre>
   *
   * <code>.gnmi.Error message = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated public com.github.gnmi.proto.Error getMessage() {
    return message_ == null ? com.github.gnmi.proto.Error.getDefaultInstance() : message_;
  }
  /**
   * <pre>
   * The overall status of the transaction.
   * </pre>
   *
   * <code>.gnmi.Error message = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated public com.github.gnmi.proto.ErrorOrBuilder getMessageOrBuilder() {
    return getMessage();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_;
  /**
   * <pre>
   * Timestamp of transaction (ns since epoch).
   * </pre>
   *
   * <code>int64 timestamp = 4;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int EXTENSION_FIELD_NUMBER = 5;
  private java.util.List<gnmi_ext.GnmiExt.Extension> extension_;
  /**
   * <pre>
   * Extension messages associated with the SetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public java.util.List<gnmi_ext.GnmiExt.Extension> getExtensionList() {
    return extension_;
  }
  /**
   * <pre>
   * Extension messages associated with the SetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public java.util.List<? extends gnmi_ext.GnmiExt.ExtensionOrBuilder> 
      getExtensionOrBuilderList() {
    return extension_;
  }
  /**
   * <pre>
   * Extension messages associated with the SetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public int getExtensionCount() {
    return extension_.size();
  }
  /**
   * <pre>
   * Extension messages associated with the SetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public gnmi_ext.GnmiExt.Extension getExtension(int index) {
    return extension_.get(index);
  }
  /**
   * <pre>
   * Extension messages associated with the SetResponse. See the
   * gNMI extension specification for further definition.
   * </pre>
   *
   * <code>repeated .gnmi_ext.Extension extension = 5;</code>
   */
  public gnmi_ext.GnmiExt.ExtensionOrBuilder getExtensionOrBuilder(
      int index) {
    return extension_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (prefix_ != null) {
      output.writeMessage(1, getPrefix());
    }
    for (int i = 0; i < response_.size(); i++) {
      output.writeMessage(2, response_.get(i));
    }
    if (message_ != null) {
      output.writeMessage(3, getMessage());
    }
    if (timestamp_ != 0L) {
      output.writeInt64(4, timestamp_);
    }
    for (int i = 0; i < extension_.size(); i++) {
      output.writeMessage(5, extension_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (prefix_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPrefix());
    }
    for (int i = 0; i < response_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, response_.get(i));
    }
    if (message_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMessage());
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, timestamp_);
    }
    for (int i = 0; i < extension_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, extension_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.gnmi.proto.SetResponse)) {
      return super.equals(obj);
    }
    com.github.gnmi.proto.SetResponse other = (com.github.gnmi.proto.SetResponse) obj;

    boolean result = true;
    result = result && (hasPrefix() == other.hasPrefix());
    if (hasPrefix()) {
      result = result && getPrefix()
          .equals(other.getPrefix());
    }
    result = result && getResponseList()
        .equals(other.getResponseList());
    result = result && (hasMessage() == other.hasMessage());
    if (hasMessage()) {
      result = result && getMessage()
          .equals(other.getMessage());
    }
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && getExtensionList()
        .equals(other.getExtensionList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPrefix()) {
      hash = (37 * hash) + PREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getPrefix().hashCode();
    }
    if (getResponseCount() > 0) {
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseList().hashCode();
    }
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (getExtensionCount() > 0) {
      hash = (37 * hash) + EXTENSION_FIELD_NUMBER;
      hash = (53 * hash) + getExtensionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.gnmi.proto.SetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.SetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.SetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.gnmi.proto.SetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * SetResponse is the response to a SetRequest, sent from the target to the
   * client. It reports the result of the modifications to the data tree that were
   * specified by the client. Errors for this RPC should be reported using the
   * https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto
   * message in the RPC return. The gnmi.Error message can be used to add
   * additional details where required. Reference: gNMI Specification
   * Section 3.4.2
   * </pre>
   *
   * Protobuf type {@code gnmi.SetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gnmi.SetResponse)
      com.github.gnmi.proto.SetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.gnmi.proto.SetResponse.class, com.github.gnmi.proto.SetResponse.Builder.class);
    }

    // Construct using com.github.gnmi.proto.SetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResponseFieldBuilder();
        getExtensionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (prefixBuilder_ == null) {
        prefix_ = null;
      } else {
        prefix_ = null;
        prefixBuilder_ = null;
      }
      if (responseBuilder_ == null) {
        response_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        responseBuilder_.clear();
      }
      if (messageBuilder_ == null) {
        message_ = null;
      } else {
        message_ = null;
        messageBuilder_ = null;
      }
      timestamp_ = 0L;

      if (extensionBuilder_ == null) {
        extension_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        extensionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_SetResponse_descriptor;
    }

    @java.lang.Override
    public com.github.gnmi.proto.SetResponse getDefaultInstanceForType() {
      return com.github.gnmi.proto.SetResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.gnmi.proto.SetResponse build() {
      com.github.gnmi.proto.SetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.gnmi.proto.SetResponse buildPartial() {
      com.github.gnmi.proto.SetResponse result = new com.github.gnmi.proto.SetResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (prefixBuilder_ == null) {
        result.prefix_ = prefix_;
      } else {
        result.prefix_ = prefixBuilder_.build();
      }
      if (responseBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          response_ = java.util.Collections.unmodifiableList(response_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.response_ = response_;
      } else {
        result.response_ = responseBuilder_.build();
      }
      if (messageBuilder_ == null) {
        result.message_ = message_;
      } else {
        result.message_ = messageBuilder_.build();
      }
      result.timestamp_ = timestamp_;
      if (extensionBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          extension_ = java.util.Collections.unmodifiableList(extension_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.extension_ = extension_;
      } else {
        result.extension_ = extensionBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.gnmi.proto.SetResponse) {
        return mergeFrom((com.github.gnmi.proto.SetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.gnmi.proto.SetResponse other) {
      if (other == com.github.gnmi.proto.SetResponse.getDefaultInstance()) return this;
      if (other.hasPrefix()) {
        mergePrefix(other.getPrefix());
      }
      if (responseBuilder_ == null) {
        if (!other.response_.isEmpty()) {
          if (response_.isEmpty()) {
            response_ = other.response_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureResponseIsMutable();
            response_.addAll(other.response_);
          }
          onChanged();
        }
      } else {
        if (!other.response_.isEmpty()) {
          if (responseBuilder_.isEmpty()) {
            responseBuilder_.dispose();
            responseBuilder_ = null;
            response_ = other.response_;
            bitField0_ = (bitField0_ & ~0x00000002);
            responseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResponseFieldBuilder() : null;
          } else {
            responseBuilder_.addAllMessages(other.response_);
          }
        }
      }
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (extensionBuilder_ == null) {
        if (!other.extension_.isEmpty()) {
          if (extension_.isEmpty()) {
            extension_ = other.extension_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureExtensionIsMutable();
            extension_.addAll(other.extension_);
          }
          onChanged();
        }
      } else {
        if (!other.extension_.isEmpty()) {
          if (extensionBuilder_.isEmpty()) {
            extensionBuilder_.dispose();
            extensionBuilder_ = null;
            extension_ = other.extension_;
            bitField0_ = (bitField0_ & ~0x00000010);
            extensionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtensionFieldBuilder() : null;
          } else {
            extensionBuilder_.addAllMessages(other.extension_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.gnmi.proto.SetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.gnmi.proto.SetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.github.gnmi.proto.Path prefix_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> prefixBuilder_;
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public boolean hasPrefix() {
      return prefixBuilder_ != null || prefix_ != null;
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public com.github.gnmi.proto.Path getPrefix() {
      if (prefixBuilder_ == null) {
        return prefix_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
      } else {
        return prefixBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder setPrefix(com.github.gnmi.proto.Path value) {
      if (prefixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        prefix_ = value;
        onChanged();
      } else {
        prefixBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder setPrefix(
        com.github.gnmi.proto.Path.Builder builderForValue) {
      if (prefixBuilder_ == null) {
        prefix_ = builderForValue.build();
        onChanged();
      } else {
        prefixBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder mergePrefix(com.github.gnmi.proto.Path value) {
      if (prefixBuilder_ == null) {
        if (prefix_ != null) {
          prefix_ =
            com.github.gnmi.proto.Path.newBuilder(prefix_).mergeFrom(value).buildPartial();
        } else {
          prefix_ = value;
        }
        onChanged();
      } else {
        prefixBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public Builder clearPrefix() {
      if (prefixBuilder_ == null) {
        prefix_ = null;
        onChanged();
      } else {
        prefix_ = null;
        prefixBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public com.github.gnmi.proto.Path.Builder getPrefixBuilder() {
      
      onChanged();
      return getPrefixFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    public com.github.gnmi.proto.PathOrBuilder getPrefixOrBuilder() {
      if (prefixBuilder_ != null) {
        return prefixBuilder_.getMessageOrBuilder();
      } else {
        return prefix_ == null ?
            com.github.gnmi.proto.Path.getDefaultInstance() : prefix_;
      }
    }
    /**
     * <pre>
     * Prefix used for paths.
     * </pre>
     *
     * <code>.gnmi.Path prefix = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> 
        getPrefixFieldBuilder() {
      if (prefixBuilder_ == null) {
        prefixBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder>(
                getPrefix(),
                getParentForChildren(),
                isClean());
        prefix_ = null;
      }
      return prefixBuilder_;
    }

    private java.util.List<com.github.gnmi.proto.UpdateResult> response_ =
      java.util.Collections.emptyList();
    private void ensureResponseIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        response_ = new java.util.ArrayList<com.github.gnmi.proto.UpdateResult>(response_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.UpdateResult, com.github.gnmi.proto.UpdateResult.Builder, com.github.gnmi.proto.UpdateResultOrBuilder> responseBuilder_;

    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public java.util.List<com.github.gnmi.proto.UpdateResult> getResponseList() {
      if (responseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(response_);
      } else {
        return responseBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public int getResponseCount() {
      if (responseBuilder_ == null) {
        return response_.size();
      } else {
        return responseBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public com.github.gnmi.proto.UpdateResult getResponse(int index) {
      if (responseBuilder_ == null) {
        return response_.get(index);
      } else {
        return responseBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder setResponse(
        int index, com.github.gnmi.proto.UpdateResult value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.set(index, value);
        onChanged();
      } else {
        responseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder setResponse(
        int index, com.github.gnmi.proto.UpdateResult.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.set(index, builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder addResponse(com.github.gnmi.proto.UpdateResult value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.add(value);
        onChanged();
      } else {
        responseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder addResponse(
        int index, com.github.gnmi.proto.UpdateResult value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.add(index, value);
        onChanged();
      } else {
        responseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder addResponse(
        com.github.gnmi.proto.UpdateResult.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.add(builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder addResponse(
        int index, com.github.gnmi.proto.UpdateResult.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.add(index, builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder addAllResponse(
        java.lang.Iterable<? extends com.github.gnmi.proto.UpdateResult> values) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, response_);
        onChanged();
      } else {
        responseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        response_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public Builder removeResponse(int index) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.remove(index);
        onChanged();
      } else {
        responseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public com.github.gnmi.proto.UpdateResult.Builder getResponseBuilder(
        int index) {
      return getResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public com.github.gnmi.proto.UpdateResultOrBuilder getResponseOrBuilder(
        int index) {
      if (responseBuilder_ == null) {
        return response_.get(index);  } else {
        return responseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public java.util.List<? extends com.github.gnmi.proto.UpdateResultOrBuilder> 
         getResponseOrBuilderList() {
      if (responseBuilder_ != null) {
        return responseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(response_);
      }
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public com.github.gnmi.proto.UpdateResult.Builder addResponseBuilder() {
      return getResponseFieldBuilder().addBuilder(
          com.github.gnmi.proto.UpdateResult.getDefaultInstance());
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public com.github.gnmi.proto.UpdateResult.Builder addResponseBuilder(
        int index) {
      return getResponseFieldBuilder().addBuilder(
          index, com.github.gnmi.proto.UpdateResult.getDefaultInstance());
    }
    /**
     * <pre>
     * A set of responses specifying the result of the operations specified in
     * the SetRequest.
     * </pre>
     *
     * <code>repeated .gnmi.UpdateResult response = 2;</code>
     */
    public java.util.List<com.github.gnmi.proto.UpdateResult.Builder> 
         getResponseBuilderList() {
      return getResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.gnmi.proto.UpdateResult, com.github.gnmi.proto.UpdateResult.Builder, com.github.gnmi.proto.UpdateResultOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        responseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.gnmi.proto.UpdateResult, com.github.gnmi.proto.UpdateResult.Builder, com.github.gnmi.proto.UpdateResultOrBuilder>(
                response_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      return responseBuilder_;
    }

    private com.github.gnmi.proto.Error message_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Error, com.github.gnmi.proto.Error.Builder, com.github.gnmi.proto.ErrorOrBuilder> messageBuilder_;
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public boolean hasMessage() {
      return messageBuilder_ != null || message_ != null;
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.github.gnmi.proto.Error getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? com.github.gnmi.proto.Error.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setMessage(com.github.gnmi.proto.Error value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setMessage(
        com.github.gnmi.proto.Error.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder mergeMessage(com.github.gnmi.proto.Error value) {
      if (messageBuilder_ == null) {
        if (message_ != null) {
          message_ =
            com.github.gnmi.proto.Error.newBuilder(message_).mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        messageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearMessage() {
      if (messageBuilder_ == null) {
        message_ = null;
        onChanged();
      } else {
        message_ = null;
        messageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.github.gnmi.proto.Error.Builder getMessageBuilder() {
      
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.github.gnmi.proto.ErrorOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            com.github.gnmi.proto.Error.getDefaultInstance() : message_;
      }
    }
    /**
     * <pre>
     * The overall status of the transaction.
     * </pre>
     *
     * <code>.gnmi.Error message = 3 [deprecated = true];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Error, com.github.gnmi.proto.Error.Builder, com.github.gnmi.proto.ErrorOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.gnmi.proto.Error, com.github.gnmi.proto.Error.Builder, com.github.gnmi.proto.ErrorOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * Timestamp of transaction (ns since epoch).
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Timestamp of transaction (ns since epoch).
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp of transaction (ns since epoch).
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<gnmi_ext.GnmiExt.Extension> extension_ =
      java.util.Collections.emptyList();
    private void ensureExtensionIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        extension_ = new java.util.ArrayList<gnmi_ext.GnmiExt.Extension>(extension_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        gnmi_ext.GnmiExt.Extension, gnmi_ext.GnmiExt.Extension.Builder, gnmi_ext.GnmiExt.ExtensionOrBuilder> extensionBuilder_;

    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public java.util.List<gnmi_ext.GnmiExt.Extension> getExtensionList() {
      if (extensionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extension_);
      } else {
        return extensionBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public int getExtensionCount() {
      if (extensionBuilder_ == null) {
        return extension_.size();
      } else {
        return extensionBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension getExtension(int index) {
      if (extensionBuilder_ == null) {
        return extension_.get(index);
      } else {
        return extensionBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder setExtension(
        int index, gnmi_ext.GnmiExt.Extension value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.set(index, value);
        onChanged();
      } else {
        extensionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder setExtension(
        int index, gnmi_ext.GnmiExt.Extension.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.set(index, builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(gnmi_ext.GnmiExt.Extension value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.add(value);
        onChanged();
      } else {
        extensionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(
        int index, gnmi_ext.GnmiExt.Extension value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.add(index, value);
        onChanged();
      } else {
        extensionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(
        gnmi_ext.GnmiExt.Extension.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.add(builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addExtension(
        int index, gnmi_ext.GnmiExt.Extension.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.add(index, builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder addAllExtension(
        java.lang.Iterable<? extends gnmi_ext.GnmiExt.Extension> values) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extension_);
        onChanged();
      } else {
        extensionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder clearExtension() {
      if (extensionBuilder_ == null) {
        extension_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        extensionBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public Builder removeExtension(int index) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.remove(index);
        onChanged();
      } else {
        extensionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension.Builder getExtensionBuilder(
        int index) {
      return getExtensionFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.ExtensionOrBuilder getExtensionOrBuilder(
        int index) {
      if (extensionBuilder_ == null) {
        return extension_.get(index);  } else {
        return extensionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public java.util.List<? extends gnmi_ext.GnmiExt.ExtensionOrBuilder> 
         getExtensionOrBuilderList() {
      if (extensionBuilder_ != null) {
        return extensionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extension_);
      }
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension.Builder addExtensionBuilder() {
      return getExtensionFieldBuilder().addBuilder(
          gnmi_ext.GnmiExt.Extension.getDefaultInstance());
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public gnmi_ext.GnmiExt.Extension.Builder addExtensionBuilder(
        int index) {
      return getExtensionFieldBuilder().addBuilder(
          index, gnmi_ext.GnmiExt.Extension.getDefaultInstance());
    }
    /**
     * <pre>
     * Extension messages associated with the SetResponse. See the
     * gNMI extension specification for further definition.
     * </pre>
     *
     * <code>repeated .gnmi_ext.Extension extension = 5;</code>
     */
    public java.util.List<gnmi_ext.GnmiExt.Extension.Builder> 
         getExtensionBuilderList() {
      return getExtensionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        gnmi_ext.GnmiExt.Extension, gnmi_ext.GnmiExt.Extension.Builder, gnmi_ext.GnmiExt.ExtensionOrBuilder> 
        getExtensionFieldBuilder() {
      if (extensionBuilder_ == null) {
        extensionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            gnmi_ext.GnmiExt.Extension, gnmi_ext.GnmiExt.Extension.Builder, gnmi_ext.GnmiExt.ExtensionOrBuilder>(
                extension_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        extension_ = null;
      }
      return extensionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gnmi.SetResponse)
  }

  // @@protoc_insertion_point(class_scope:gnmi.SetResponse)
  private static final com.github.gnmi.proto.SetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.gnmi.proto.SetResponse();
  }

  public static com.github.gnmi.proto.SetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetResponse>
      PARSER = new com.google.protobuf.AbstractParser<SetResponse>() {
    @java.lang.Override
    public SetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.gnmi.proto.SetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

