// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

/**
 * <pre>
 * Update is a re-usable message that is used to store a particular Path,
 * Value pair.
 * Reference: gNMI Specification Section 2.1
 * </pre>
 *
 * Protobuf type {@code gnmi.Update}
 */
public  final class Update extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gnmi.Update)
    UpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Update.newBuilder() to construct.
  private Update(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Update() {
    duplicates_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Update(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.github.gnmi.proto.Path.Builder subBuilder = null;
            if (path_ != null) {
              subBuilder = path_.toBuilder();
            }
            path_ = input.readMessage(com.github.gnmi.proto.Path.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(path_);
              path_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.github.gnmi.proto.Value.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(com.github.gnmi.proto.Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.github.gnmi.proto.TypedValue.Builder subBuilder = null;
            if (val_ != null) {
              subBuilder = val_.toBuilder();
            }
            val_ = input.readMessage(com.github.gnmi.proto.TypedValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(val_);
              val_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            duplicates_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Update_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Update_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.gnmi.proto.Update.class, com.github.gnmi.proto.Update.Builder.class);
  }

  public static final int PATH_FIELD_NUMBER = 1;
  private com.github.gnmi.proto.Path path_;
  /**
   * <pre>
   * The path (key) for the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 1;</code>
   */
  public boolean hasPath() {
    return path_ != null;
  }
  /**
   * <pre>
   * The path (key) for the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 1;</code>
   */
  public com.github.gnmi.proto.Path getPath() {
    return path_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : path_;
  }
  /**
   * <pre>
   * The path (key) for the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 1;</code>
   */
  public com.github.gnmi.proto.PathOrBuilder getPathOrBuilder() {
    return getPath();
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private com.github.gnmi.proto.Value value_;
  /**
   * <pre>
   * The value (value) for the update.
   * </pre>
   *
   * <code>.gnmi.Value value = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <pre>
   * The value (value) for the update.
   * </pre>
   *
   * <code>.gnmi.Value value = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated public com.github.gnmi.proto.Value getValue() {
    return value_ == null ? com.github.gnmi.proto.Value.getDefaultInstance() : value_;
  }
  /**
   * <pre>
   * The value (value) for the update.
   * </pre>
   *
   * <code>.gnmi.Value value = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated public com.github.gnmi.proto.ValueOrBuilder getValueOrBuilder() {
    return getValue();
  }

  public static final int VAL_FIELD_NUMBER = 3;
  private com.github.gnmi.proto.TypedValue val_;
  /**
   * <pre>
   * The explicitly typed update value.
   * </pre>
   *
   * <code>.gnmi.TypedValue val = 3;</code>
   */
  public boolean hasVal() {
    return val_ != null;
  }
  /**
   * <pre>
   * The explicitly typed update value.
   * </pre>
   *
   * <code>.gnmi.TypedValue val = 3;</code>
   */
  public com.github.gnmi.proto.TypedValue getVal() {
    return val_ == null ? com.github.gnmi.proto.TypedValue.getDefaultInstance() : val_;
  }
  /**
   * <pre>
   * The explicitly typed update value.
   * </pre>
   *
   * <code>.gnmi.TypedValue val = 3;</code>
   */
  public com.github.gnmi.proto.TypedValueOrBuilder getValOrBuilder() {
    return getVal();
  }

  public static final int DUPLICATES_FIELD_NUMBER = 4;
  private int duplicates_;
  /**
   * <pre>
   * Number of coalesced duplicates.
   * </pre>
   *
   * <code>uint32 duplicates = 4;</code>
   */
  public int getDuplicates() {
    return duplicates_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (path_ != null) {
      output.writeMessage(1, getPath());
    }
    if (value_ != null) {
      output.writeMessage(2, getValue());
    }
    if (val_ != null) {
      output.writeMessage(3, getVal());
    }
    if (duplicates_ != 0) {
      output.writeUInt32(4, duplicates_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (path_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPath());
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValue());
    }
    if (val_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getVal());
    }
    if (duplicates_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, duplicates_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.gnmi.proto.Update)) {
      return super.equals(obj);
    }
    com.github.gnmi.proto.Update other = (com.github.gnmi.proto.Update) obj;

    boolean result = true;
    result = result && (hasPath() == other.hasPath());
    if (hasPath()) {
      result = result && getPath()
          .equals(other.getPath());
    }
    result = result && (hasValue() == other.hasValue());
    if (hasValue()) {
      result = result && getValue()
          .equals(other.getValue());
    }
    result = result && (hasVal() == other.hasVal());
    if (hasVal()) {
      result = result && getVal()
          .equals(other.getVal());
    }
    result = result && (getDuplicates()
        == other.getDuplicates());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPath()) {
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
    }
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    if (hasVal()) {
      hash = (37 * hash) + VAL_FIELD_NUMBER;
      hash = (53 * hash) + getVal().hashCode();
    }
    hash = (37 * hash) + DUPLICATES_FIELD_NUMBER;
    hash = (53 * hash) + getDuplicates();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.gnmi.proto.Update parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.Update parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.Update parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.Update parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.Update parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.gnmi.proto.Update parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.gnmi.proto.Update parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.Update parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.Update parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.Update parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.gnmi.proto.Update parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.gnmi.proto.Update parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.gnmi.proto.Update prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Update is a re-usable message that is used to store a particular Path,
   * Value pair.
   * Reference: gNMI Specification Section 2.1
   * </pre>
   *
   * Protobuf type {@code gnmi.Update}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gnmi.Update)
      com.github.gnmi.proto.UpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Update_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.gnmi.proto.Update.class, com.github.gnmi.proto.Update.Builder.class);
    }

    // Construct using com.github.gnmi.proto.Update.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pathBuilder_ == null) {
        path_ = null;
      } else {
        path_ = null;
        pathBuilder_ = null;
      }
      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      if (valBuilder_ == null) {
        val_ = null;
      } else {
        val_ = null;
        valBuilder_ = null;
      }
      duplicates_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.gnmi.proto.GnmiProto.internal_static_gnmi_Update_descriptor;
    }

    @java.lang.Override
    public com.github.gnmi.proto.Update getDefaultInstanceForType() {
      return com.github.gnmi.proto.Update.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.gnmi.proto.Update build() {
      com.github.gnmi.proto.Update result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.gnmi.proto.Update buildPartial() {
      com.github.gnmi.proto.Update result = new com.github.gnmi.proto.Update(this);
      if (pathBuilder_ == null) {
        result.path_ = path_;
      } else {
        result.path_ = pathBuilder_.build();
      }
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      if (valBuilder_ == null) {
        result.val_ = val_;
      } else {
        result.val_ = valBuilder_.build();
      }
      result.duplicates_ = duplicates_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.gnmi.proto.Update) {
        return mergeFrom((com.github.gnmi.proto.Update)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.gnmi.proto.Update other) {
      if (other == com.github.gnmi.proto.Update.getDefaultInstance()) return this;
      if (other.hasPath()) {
        mergePath(other.getPath());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (other.hasVal()) {
        mergeVal(other.getVal());
      }
      if (other.getDuplicates() != 0) {
        setDuplicates(other.getDuplicates());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.gnmi.proto.Update parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.gnmi.proto.Update) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.gnmi.proto.Path path_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> pathBuilder_;
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public boolean hasPath() {
      return pathBuilder_ != null || path_ != null;
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public com.github.gnmi.proto.Path getPath() {
      if (pathBuilder_ == null) {
        return path_ == null ? com.github.gnmi.proto.Path.getDefaultInstance() : path_;
      } else {
        return pathBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public Builder setPath(com.github.gnmi.proto.Path value) {
      if (pathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        path_ = value;
        onChanged();
      } else {
        pathBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public Builder setPath(
        com.github.gnmi.proto.Path.Builder builderForValue) {
      if (pathBuilder_ == null) {
        path_ = builderForValue.build();
        onChanged();
      } else {
        pathBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public Builder mergePath(com.github.gnmi.proto.Path value) {
      if (pathBuilder_ == null) {
        if (path_ != null) {
          path_ =
            com.github.gnmi.proto.Path.newBuilder(path_).mergeFrom(value).buildPartial();
        } else {
          path_ = value;
        }
        onChanged();
      } else {
        pathBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public Builder clearPath() {
      if (pathBuilder_ == null) {
        path_ = null;
        onChanged();
      } else {
        path_ = null;
        pathBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public com.github.gnmi.proto.Path.Builder getPathBuilder() {
      
      onChanged();
      return getPathFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    public com.github.gnmi.proto.PathOrBuilder getPathOrBuilder() {
      if (pathBuilder_ != null) {
        return pathBuilder_.getMessageOrBuilder();
      } else {
        return path_ == null ?
            com.github.gnmi.proto.Path.getDefaultInstance() : path_;
      }
    }
    /**
     * <pre>
     * The path (key) for the update.
     * </pre>
     *
     * <code>.gnmi.Path path = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder> 
        getPathFieldBuilder() {
      if (pathBuilder_ == null) {
        pathBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.gnmi.proto.Path, com.github.gnmi.proto.Path.Builder, com.github.gnmi.proto.PathOrBuilder>(
                getPath(),
                getParentForChildren(),
                isClean());
        path_ = null;
      }
      return pathBuilder_;
    }

    private com.github.gnmi.proto.Value value_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Value, com.github.gnmi.proto.Value.Builder, com.github.gnmi.proto.ValueOrBuilder> valueBuilder_;
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.github.gnmi.proto.Value getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? com.github.gnmi.proto.Value.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setValue(com.github.gnmi.proto.Value value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setValue(
        com.github.gnmi.proto.Value.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder mergeValue(com.github.gnmi.proto.Value value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            com.github.gnmi.proto.Value.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.github.gnmi.proto.Value.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.github.gnmi.proto.ValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            com.github.gnmi.proto.Value.getDefaultInstance() : value_;
      }
    }
    /**
     * <pre>
     * The value (value) for the update.
     * </pre>
     *
     * <code>.gnmi.Value value = 2 [deprecated = true];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.Value, com.github.gnmi.proto.Value.Builder, com.github.gnmi.proto.ValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.gnmi.proto.Value, com.github.gnmi.proto.Value.Builder, com.github.gnmi.proto.ValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private com.github.gnmi.proto.TypedValue val_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.TypedValue, com.github.gnmi.proto.TypedValue.Builder, com.github.gnmi.proto.TypedValueOrBuilder> valBuilder_;
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public boolean hasVal() {
      return valBuilder_ != null || val_ != null;
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public com.github.gnmi.proto.TypedValue getVal() {
      if (valBuilder_ == null) {
        return val_ == null ? com.github.gnmi.proto.TypedValue.getDefaultInstance() : val_;
      } else {
        return valBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public Builder setVal(com.github.gnmi.proto.TypedValue value) {
      if (valBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        val_ = value;
        onChanged();
      } else {
        valBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public Builder setVal(
        com.github.gnmi.proto.TypedValue.Builder builderForValue) {
      if (valBuilder_ == null) {
        val_ = builderForValue.build();
        onChanged();
      } else {
        valBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public Builder mergeVal(com.github.gnmi.proto.TypedValue value) {
      if (valBuilder_ == null) {
        if (val_ != null) {
          val_ =
            com.github.gnmi.proto.TypedValue.newBuilder(val_).mergeFrom(value).buildPartial();
        } else {
          val_ = value;
        }
        onChanged();
      } else {
        valBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public Builder clearVal() {
      if (valBuilder_ == null) {
        val_ = null;
        onChanged();
      } else {
        val_ = null;
        valBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public com.github.gnmi.proto.TypedValue.Builder getValBuilder() {
      
      onChanged();
      return getValFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    public com.github.gnmi.proto.TypedValueOrBuilder getValOrBuilder() {
      if (valBuilder_ != null) {
        return valBuilder_.getMessageOrBuilder();
      } else {
        return val_ == null ?
            com.github.gnmi.proto.TypedValue.getDefaultInstance() : val_;
      }
    }
    /**
     * <pre>
     * The explicitly typed update value.
     * </pre>
     *
     * <code>.gnmi.TypedValue val = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.gnmi.proto.TypedValue, com.github.gnmi.proto.TypedValue.Builder, com.github.gnmi.proto.TypedValueOrBuilder> 
        getValFieldBuilder() {
      if (valBuilder_ == null) {
        valBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.gnmi.proto.TypedValue, com.github.gnmi.proto.TypedValue.Builder, com.github.gnmi.proto.TypedValueOrBuilder>(
                getVal(),
                getParentForChildren(),
                isClean());
        val_ = null;
      }
      return valBuilder_;
    }

    private int duplicates_ ;
    /**
     * <pre>
     * Number of coalesced duplicates.
     * </pre>
     *
     * <code>uint32 duplicates = 4;</code>
     */
    public int getDuplicates() {
      return duplicates_;
    }
    /**
     * <pre>
     * Number of coalesced duplicates.
     * </pre>
     *
     * <code>uint32 duplicates = 4;</code>
     */
    public Builder setDuplicates(int value) {
      
      duplicates_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of coalesced duplicates.
     * </pre>
     *
     * <code>uint32 duplicates = 4;</code>
     */
    public Builder clearDuplicates() {
      
      duplicates_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gnmi.Update)
  }

  // @@protoc_insertion_point(class_scope:gnmi.Update)
  private static final com.github.gnmi.proto.Update DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.gnmi.proto.Update();
  }

  public static com.github.gnmi.proto.Update getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Update>
      PARSER = new com.google.protobuf.AbstractParser<Update>() {
    @java.lang.Override
    public Update parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Update(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Update> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Update> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.gnmi.proto.Update getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

