// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface UpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.Update)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The path (key) for the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 1;</code>
   */
  boolean hasPath();
  /**
   * <pre>
   * The path (key) for the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 1;</code>
   */
  com.github.gnmi.proto.Path getPath();
  /**
   * <pre>
   * The path (key) for the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 1;</code>
   */
  com.github.gnmi.proto.PathOrBuilder getPathOrBuilder();

  /**
   * <pre>
   * The value (value) for the update.
   * </pre>
   *
   * <code>.gnmi.Value value = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasValue();
  /**
   * <pre>
   * The value (value) for the update.
   * </pre>
   *
   * <code>.gnmi.Value value = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.github.gnmi.proto.Value getValue();
  /**
   * <pre>
   * The value (value) for the update.
   * </pre>
   *
   * <code>.gnmi.Value value = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.github.gnmi.proto.ValueOrBuilder getValueOrBuilder();

  /**
   * <pre>
   * The explicitly typed update value.
   * </pre>
   *
   * <code>.gnmi.TypedValue val = 3;</code>
   */
  boolean hasVal();
  /**
   * <pre>
   * The explicitly typed update value.
   * </pre>
   *
   * <code>.gnmi.TypedValue val = 3;</code>
   */
  com.github.gnmi.proto.TypedValue getVal();
  /**
   * <pre>
   * The explicitly typed update value.
   * </pre>
   *
   * <code>.gnmi.TypedValue val = 3;</code>
   */
  com.github.gnmi.proto.TypedValueOrBuilder getValOrBuilder();

  /**
   * <pre>
   * Number of coalesced duplicates.
   * </pre>
   *
   * <code>uint32 duplicates = 4;</code>
   */
  int getDuplicates();
}
