// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

public interface UpdateResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.UpdateResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Deprecated timestamp for the UpdateResult, this field has been
   * replaced by the timestamp within the SetResponse message, since
   * all mutations effected by a set should be applied as a single
   * transaction.
   * </pre>
   *
   * <code>int64 timestamp = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated long getTimestamp();

  /**
   * <pre>
   * Path associated with the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 2;</code>
   */
  boolean hasPath();
  /**
   * <pre>
   * Path associated with the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 2;</code>
   */
  com.github.gnmi.proto.Path getPath();
  /**
   * <pre>
   * Path associated with the update.
   * </pre>
   *
   * <code>.gnmi.Path path = 2;</code>
   */
  com.github.gnmi.proto.PathOrBuilder getPathOrBuilder();

  /**
   * <pre>
   * Status of the update operation.
   * </pre>
   *
   * <code>.gnmi.Error message = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasMessage();
  /**
   * <pre>
   * Status of the update operation.
   * </pre>
   *
   * <code>.gnmi.Error message = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.github.gnmi.proto.Error getMessage();
  /**
   * <pre>
   * Status of the update operation.
   * </pre>
   *
   * <code>.gnmi.Error message = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.github.gnmi.proto.ErrorOrBuilder getMessageOrBuilder();

  /**
   * <pre>
   * Update operation type.
   * </pre>
   *
   * <code>.gnmi.UpdateResult.Operation op = 4;</code>
   */
  int getOpValue();
  /**
   * <pre>
   * Update operation type.
   * </pre>
   *
   * <code>.gnmi.UpdateResult.Operation op = 4;</code>
   */
  com.github.gnmi.proto.UpdateResult.Operation getOp();
}
