// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnmi.proto

package com.github.gnmi.proto;

@java.lang.Deprecated public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gnmi.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Value of the variable being transmitted.
   * </pre>
   *
   * <code>bytes value = 1;</code>
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <pre>
   * Encoding used for the value field.
   * </pre>
   *
   * <code>.gnmi.Encoding type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   * Encoding used for the value field.
   * </pre>
   *
   * <code>.gnmi.Encoding type = 2;</code>
   */
  com.github.gnmi.proto.Encoding getType();
}
