// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package org.example;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
