// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package org.example;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
